// apps/ui/src/containers/projects/ProjectDates.vue
<script setup lang="ts">
import { useProjectsStore } from "@/stores/projects";
import type { UUID } from "crypto";
import type { Dayjs } from "dayjs";
import { computed } from "vue";
import { useEventsStore } from "@/stores/events";
import { updateProjectMutation } from "@/mutations/projects";

const projectsStore = useProjectsStore();
const eventsStore = useEventsStore();

const props = defineProps<{
  projectId: UUID;
}>();

const project = computed(() => projectsStore.getProjectById(props.projectId));

const handleStartDateChange = (date: Dayjs | null) => {
  if (!project.value) return;

  if (date === null) {
    project.value.startDate = null;
    project.value.endDate = null;
  } else {
    project.value.startDate = date;
  }

  eventsStore.sendEvent({
    name: "updateProject",
    mutation: updateProjectMutation,
    variables: {
      id: project.value.id,
      startDate: date === null ? null : date.format("YYYY-MM-DD"),
    },
    rollbackData: { ...project.value },
  });
};

const handleEndDateChange = (date: Dayjs | null) => {
  if (!project.value) return;

  project.value.endDate = date;

  eventsStore.sendEvent({
    name: "updateProject",
    mutation: updateProjectMutation,
    variables: {
      id: project.value.id,
      endDate: date === null ? null : date.format("YYYY-MM-DD"),
    },
    rollbackData: { ...project.value },
  });
};
</script>

<template>
  <div v-if="project" class="flex items-center">
    <TDatePicker
      v-slot="{ open, value }"
      :model-value="project.startDate"
      @update:model-value="handleStartDateChange"
    >
      <div
        class="flex items-center px-2 rounded w-32 h-8"
        :class="open ? 'bg-primary-600' : 'hover:bg-primary-600'"
      >
        <i class="mdi mr-2 text-white mdi-calendar" />
        <div
          class="text-sm whitespace-nowrap"
          :class="value ? 'text-white' : 'text-primary-200'"
        >
          {{ value?.format("MMM DD") ?? "Start date" }}
        </div>

        <div class="flex-1" />
        <i
          v-if="open"
          class="mdi mdi-close text-primary-100 hover:text-white ml-2 mt-0.5"
          @click.prevent="handleStartDateChange(null)"
        />
      </div>
    </TDatePicker>

    <i class="mdi mdi-arrow-right-thin text-primary-600 mx-1" />

    <TDatePicker
      v-slot="{ open, value, disabled }"
      :model-value="project.endDate"
      :disabled="project.startDate === null"
      @update:model-value="handleEndDateChange"
    >
      <div
        class="flex items-center px-2 rounded w-32 h-8"
        :class="[
          open ? 'bg-primary-600' : '',
          disabled ? '' : 'hover:bg-primary-600',
        ]"
      >
        <i
          class="mdi mr-2 mdi-calendar"
          :class="disabled ? 'text-primary-400' : 'text-primary-200'"
        />
        <div
          class="text-sm whitespace-nowrap"
          :class="{
            'text-white': value,
            'text-primary-200': !disabled && !value,
            'text-primary-400': disabled,
          }"
        >
          {{ value?.format("MMM DD") ?? "End date" }}
        </div>

        <i
          v-if="open"
          class="mdi mdi-close text-primary-100 hover:text-white ml-2 mt-0.5"
          @click.prevent="handleEndDateChange(null)"
        />
      </div>
    </TDatePicker>
  </div>
</template>

// apps/ui-react/src/components/projects/project-dates.tsx
import { useState } from "react";
import { useStore } from "zustand";
import { projectsStore } from "@/stores/projects";
import { eventsStore } from "@/stores/events";
import { updateProjectMutation } from "@/mutations/projects";
import type { UUID } from "crypto";
import { format } from "date-fns";

import { Button } from "@/components/ui/button";
import { CalendarIcon, XIcon, ArrowRightIcon } from "lucide-react";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";

interface ProjectDatesProps {
  projectId: UUID;
}

export function ProjectDates({ projectId }: ProjectDatesProps) {
  const projects = useStore(projectsStore, (state) => state.projects);
  const updateProject = useStore(projectsStore, (state) => state.updateProject);
  const sendEvent = useStore(eventsStore, (state) => state.sendEvent);

  const project = projects.find((p) => p.id === projectId);

  if (!project) return null;

  const [startDateOpen, setStartDateOpen] = useState(false);
  const [endDateOpen, setEndDateOpen] = useState(false);

  const handleStartDateChange = (date: Date | undefined) => {
    const newStartDate = date || null;
    const newEndDate = newStartDate === null ? null : project.endDate;

    updateProject(project.id, {
      startDate: newStartDate,
      endDate: newEndDate,
    });

    sendEvent({
      name: "updateProject",
      mutation: updateProjectMutation,
      variables: {
        id: project.id,
        startDate: newStartDate ? newStartDate.toISOString().split("T")[0] : null,
        endDate: newEndDate ? newEndDate.toISOString().split("T")[0] : null,
      },
      rollbackData: { ...project },
    });
  };

  const handleEndDateChange = (date: Date | undefined) => {
    const newEndDate = date || null;

    updateProject(project.id, {
      endDate: newEndDate,
    });

    sendEvent({
      name: "updateProject",
      mutation: updateProjectMutation,
      variables: {
        id: project.id,
        endDate: newEndDate ? newEndDate.toISOString().split("T")[0] : null,
      },
      rollbackData: { ...project },
    });
  };

  return (
    <div className="flex items-center gap-1">
      <Popover open={startDateOpen} onOpenChange={setStartDateOpen}>
        <PopoverTrigger asChild>
          <Button
            variant="ghost"
            size="sm"
            className={`flex h-8 items-center gap-1 px-2 ${
              startDateOpen ? "bg-primary-600" : "hover:bg-primary-600"
            }`}
          >
            <CalendarIcon className="h-4 w-4 text-white" />
            <span
              className={`text-sm whitespace-nowrap ${
                project.startDate ? "text-white" : "text-primary-200"
              }`}
            >
              {project.startDate ? format(project.startDate, "MMM dd") : "Start date"}
            </span>
            {startDateOpen && project.startDate && (
              <Button
                variant="ghost"
                size="icon"
                className="text-primary-100 h-6 w-6 hover:text-white"
                onClick={(e) => {
                  e.preventDefault();
                  e.stopPropagation();
                  handleStartDateChange(undefined);
                }}
              >
                <XIcon className="h-3 w-3" />
              </Button>
            )}
          </Button>
        </PopoverTrigger>
        <PopoverContent className="w-auto p-0">
          <Calendar
            mode="single"
            selected={project.startDate || undefined}
            onSelect={handleStartDateChange}
            initialFocus
          />
        </PopoverContent>
      </Popover>

      <ArrowRightIcon className="text-primary-600 mx-1 h-4 w-4" />

      <Popover open={endDateOpen} onOpenChange={setEndDateOpen}>
        <PopoverTrigger asChild>
          <Button
            variant="ghost"
            size="sm"
            className={`flex h-8 items-center gap-1 px-2 ${
              (endDateOpen ? "bg-primary-600" : "",
              project.startDate === null ? "cursor-not-allowed opacity-50" : "hover:bg-primary-600")
            }`}
            disabled={project.startDate === null}
          >
            <CalendarIcon
              className={`h-4 w-4 ${
                project.startDate === null ? "text-primary-400" : "text-primary-200"
              }`}
            />
            <span
              className={`text-sm whitespace-nowrap ${
                (project.endDate ? "text-white" : "text-primary-200",
                project.startDate === null ? "text-primary-400" : "")
              }`}
            >
              {project.endDate ? format(project.endDate, "MMM dd") : "End date"}
            </span>
            {endDateOpen && project.endDate && (
              <Button
                variant="ghost"
                size="icon"
                className="text-primary-100 h-6 w-6 hover:text-white"
                onClick={(e) => {
                  e.preventDefault();
                  e.stopPropagation();
                  handleEndDateChange(undefined);
                }}
              >
                <XIcon className="h-3 w-3" />
              </Button>
            )}
          </Button>
        </PopoverTrigger>
        <PopoverContent className="w-auto p-0">
          <Calendar
            mode="single"
            selected={project.endDate || undefined}
            onSelect={handleEndDateChange}
            disabled={project.startDate === null}
          />
        </PopoverContent>
      </Popover>
    </div>
  );
}
