// apps/ui-react/src/components/movements/movements-table.tsx
import * as React from "react";
import { useStore } from "zustand";
import { movementsStore } from "@/stores/movements";
import { viewsStore } from "@/stores/views";
import { searchStore } from "@/stores/search";
import { activitiesStore } from "@/stores/activities";
import { MovementLine } from "./movement-line";
import { MovementsFilters } from "./filters/movements-filters";
import { MovementsActions } from "./movements-actions";
import { verifyMovementFilter } from "@maille/core/movements";
import { ScrollArea } from "@/components/ui/scroll-area";

import { useHotkeys } from "react-hotkeys-hook";
import type { Movement } from "@maille/core/movements";
import type { string } from "crypto";

interface MovementsTableProps {
  movements: Movement[];
  viewId: string;
  grouping?: "period" | null;
  accountFilter?: string | null;
}

export function MovementsTable({
  movements,
  viewId,
  grouping = null,
  accountFilter = null,
}: MovementsTableProps) {
  const focusedMovement = useStore(movementsStore, (state) => state.focusedMovement);
  const focusedActivity = useStore(activitiesStore, (state) => state.focusedActivity);
  const filterStringBySearch = useStore(searchStore, (state) => state.filterStringBySearch);
  const movementView = useStore(viewsStore, (state) => state.getMovementView(viewId));
  const [selectedMovements, setSelectedMovements] = React.useState<string[]>([]);

  // Cleanup on unmount
  React.useEffect(() => {
    return () => {
      if (focusedMovement) {
        movementsStore.getState().setFocusedMovement(null);
      }
      if (focusedActivity) {
        activitiesStore.getState().setFocusedActivity(null);
      }
    };
  }, []);

  // Reset focused activity when focused movement changes
  React.useEffect(() => {
    if (focusedMovement) {
      activitiesStore.getState().setFocusedActivity(null);
    }
  }, [focusedMovement]);

  const movementsFiltered = React.useMemo(() => {
    return movements
      .filter((movement) => filterStringBySearch(movement.name))
      .filter((movement) => (accountFilter !== null ? movement.account === accountFilter : true))
      .filter((movement) => {
        if (movementView.filters.length === 0) return true;
        return movementView.filters
          .map((filter) => verifyMovementFilter(filter, movement))
          .every((f) => f);
      });
  }, [movements, filterStringBySearch, accountFilter, movementView.filters]);

  const movementsSorted = React.useMemo(() => {
    return [...movementsFiltered].sort((a, b) => {
      if (a.date.getTime() !== b.date.getTime()) {
        return b.date.getTime() - a.date.getTime();
      }
      return b.id.localeCompare(a.id);
    });
  }, [movementsFiltered]);

  type Group = {
    id: string;
    month: number;
    year: number;
    movements: Movement[];
  };

  type MovementAndGroup = ({ itemType: "group" } & Group) | ({ itemType: "movement" } & Movement);

  const movementsWithGroups = React.useMemo<MovementAndGroup[]>(() => {
    if (!grouping) return movementsSorted.map((m) => ({ itemType: "movement", ...m }));

    const groups = movementsSorted.reduce((groups: Group[], m) => {
      const month = m.date.getMonth();
      const year = m.date.getFullYear();
      const group = groups.find((p) => p.month === month && p.year === year);

      if (group) {
        group.movements.push(m);
      } else {
        groups.push({
          id: `${month}-${year}`,
          month,
          year,
          movements: [m],
        });
      }

      return groups;
    }, []);

    return groups
      .sort((a, b) => {
        if (a.year !== b.year) return b.year - a.year;
        return b.month - a.month;
      })
      .reduce((mwg: MovementAndGroup[], group) => {
        mwg.push({
          itemType: "group",
          id: group.id,
          month: group.month,
          year: group.year,
        });
        return mwg.concat(group.movements.map((m) => ({ itemType: "movement", ...m })));
      }, []);
  }, [movementsSorted, grouping]);

  const periodFormatter = (month: number, year: number): string => {
    return new Date(year, month).toLocaleString("default", { month: "long", year: "numeric" });
  };

  const handleMovementClick = (movementId: string) => {
    if (focusedMovement === movementId) {
      movementsStore.getState().setFocusedMovement(null);
    } else {
      movementsStore.getState().setFocusedMovement(movementId);
    }
  };

  const selectMovement = (movementId: string) => {
    setSelectedMovements((prev) =>
      prev.includes(movementId) ? prev.filter((id) => id !== movementId) : [...prev, movementId],
    );
  };

  // Hotkeys
  useHotkeys("k", () => {
    if (movementsSorted.length === 0) return;

    const currentIndex = movementsSorted.findIndex((movement) => movement.id === focusedMovement);

    const nextIndex =
      currentIndex === -1
        ? 0
        : (currentIndex - 1 + movementsSorted.length) % movementsSorted.length;

    movementsStore.getState().setFocusedMovement(movementsSorted[nextIndex].id);
  });

  useHotkeys("j", () => {
    if (movementsSorted.length === 0) return;

    const currentIndex = movementsSorted.findIndex((movement) => movement.id === focusedMovement);

    const nextIndex = (currentIndex + 1) % movementsSorted.length;
    movementsStore.getState().setFocusedMovement(movementsSorted[nextIndex].id);
  });

  useHotkeys("escape", () => {
    if (selectedMovements.length > 0) {
      setSelectedMovements([]);
    }
  });

  useHotkeys("ctrl+a,meta+a", () => {
    setSelectedMovements(movementsFiltered.map((m) => m.id));
  });

  return (
    <div className="flex min-h-0 min-w-0 flex-1 flex-col">
      <MovementsFilters viewId={viewId} movements={movementsFiltered} />

      <div className="flex flex-1 flex-col overflow-x-hidden sm:min-w-[575px]">
        {movementsFiltered.length !== 0 ? (
          <ScrollArea className="flex-1 pb-40">
            {grouping
              ? movementsWithGroups.map((item) => (
                  <React.Fragment key={item.id}>
                    {item.itemType === "group" ? (
                      <div className="bg-primary-800 flex h-10 flex-shrink-0 items-center gap-2 border-b pl-5 sm:pl-7">
                        <i
                          className="mdi mdi-calendar-blank text-primary-100 mdi-16px"
                          aria-hidden="true"
                        />
                        <div className="text-sm font-medium">
                          {periodFormatter(item.month, item.year)}
                        </div>
                        <div className="flex-1" />
                      </div>
                    ) : (
                      <MovementLine
                        movement={item}
                        isMovementSelected={selectedMovements.includes(item.id)}
                        onSelectMovement={() => selectMovement(item.id)}
                        onClick={() => handleMovementClick(item.id)}
                      />
                    )}
                  </React.Fragment>
                ))
              : movementsSorted.map((movement) => (
                  <MovementLine
                    key={movement.id}
                    movement={movement}
                    isMovementSelected={selectedMovements.includes(movement.id)}
                    onSelectMovement={() => selectMovement(movement.id)}
                    onClick={() => handleMovementClick(movement.id)}
                  />
                ))}
          </ScrollArea>
        ) : (
          <div className="flex flex-1 items-center justify-center overflow-hidden">
            <div className="text-primary-600">No movement found</div>
          </div>
        )}
      </div>

      <MovementsActions
        selectedMovements={selectedMovements}
        onClearSelection={() => setSelectedMovements([])}
      />
    </div>
  );
}

// apps/ui/src/containers/movements/MovementsTable.vue
<script setup lang="ts">
import dayjs from "dayjs";
import _ from "lodash";
import { computed, onBeforeUnmount, ref, watch } from "vue";
import { RecycleScroller } from "vue-virtual-scroller";

import MovementLine from "@/containers/movements/MovementLine.vue";

import { useMovementsStore } from "@/stores/movements";
import { useSearchStore } from "@/stores/search";
import { useActivitiesStore } from "@/stores/activities";
import { useViewsStore } from "@/stores/views";

import type { Movement } from "@maille/core/movements";
import { verifyMovementFilter } from "@maille/core/movements";
import { storeToRefs } from "pinia";
import type { UUID } from "crypto";
import { useHotkey } from "@/hooks/use-hotkey";
import MovementsFilters from "./filters/MovementsFilters.vue";
import MovementsActions from "./MovementsActions.vue";

const movementsStore = useMovementsStore();
const { focusedMovement } = storeToRefs(movementsStore);

const activitiesStore = useActivitiesStore();
const { focusedActivity } = storeToRefs(activitiesStore);

const { filterStringBySearch } = useSearchStore();
const viewsStore = useViewsStore();

const props = withDefaults(
  defineProps<{
    movements: Movement[];
    viewId: string;
    grouping?: "period" | null;
    accountFilter?: UUID | null;
  }>(),
  { grouping: null, accountFilter: null },
);

const movementView = computed(() => viewsStore.getMovementView(props.viewId));
const selectedMovements = ref<UUID[]>([]);

onBeforeUnmount(() => {
  focusedMovement.value = null;
  focusedActivity.value = null;
});

watch(focusedMovement, () => {
  focusedActivity.value = null;
});

type Group = {
  id: string;
  month: number;
  year: number;
};

type MovementAndGroup =
  | ({ itemType: "group" } & Group)
  | ({ itemType: "movement" } & Movement);

const movementsFiltered = computed(() => {
  return props.movements
    .filter((movement) => filterStringBySearch(movement.name))
    .filter((movement) =>
      props.accountFilter !== null
        ? movement.account === props.accountFilter
        : true,
    )
    .filter((movement) => {
      if (movementView.value.filters.length === 0) return true;

      return movementView.value.filters
        .map((filter) => {
          return verifyMovementFilter(filter, movement);
        })
        .every((f) => f);
    });
});

const movementsSorted = computed(() => {
  return _.orderBy(movementsFiltered.value, ["date", "id"], ["desc", "desc"]);
});

const movementsWithGroups = computed<MovementAndGroup[]>(() => {
  const groups = movementsSorted.value.reduce(
    (groups, m) => {
      const group = groups.find(
        (p) => p.month === m.date.month() && p.year === m.date.year(),
      );

      if (group) {
        group.movements.push(m);
      } else {
        groups.push({
          id: m.date.format("MM-YYYY"),
          month: m.date.month(),
          year: m.date.year(),
          movements: [m],
        });
      }

      return groups;
    },
    [] as { id: string; month: number; year: number; movements: Movement[] }[],
  );

  return _.orderBy(groups, ["year", "month"], ["desc", "desc"]).reduce(
    (mwg, group) => {
      mwg.push({
        itemType: "group",
        id: group.id,
        month: group.month,
        year: group.year,
      });
      return mwg.concat(
        group.movements.map((m) => ({ itemType: "movement", ...m })),
      );
    },
    [] as MovementAndGroup[],
  );
});

const periodFormatter = (month: number, year: number): string => {
  return dayjs().month(month).year(year).format("MMMM YYYY");
};

const handleMovementClick = (movementId: UUID) => {
  if (focusedMovement.value === movementId) {
    focusedMovement.value = null;
  } else {
    focusedMovement.value = movementId;
  }
};

useHotkey(["j"], () => {
  const movements = movementsFiltered.value;
  if (movements.length === 0) return;

  const currentIndex = movements.findIndex(
    (movement) => movement.id === focusedMovement.value,
  );

  const nextIndex =
    currentIndex === -1
      ? 0
      : (currentIndex - 1 + movements.length) % movements.length;
  focusedMovement.value = movements[nextIndex].id;
});

useHotkey(["k"], () => {
  const movements = movementsFiltered.value;
  if (movements.length === 0) return;

  const currentIndex = movements.findIndex(
    (movement) => movement.id === focusedMovement.value,
  );

  const nextIndex = (currentIndex + 1) % movements.length;
  focusedMovement.value = movements[nextIndex].id;
});

const selectMovement = (movementId: UUID) => {
  if (selectedMovements.value.includes(movementId)) {
    selectedMovements.value = selectedMovements.value.filter(
      (id) => id !== movementId,
    );
  } else {
    selectedMovements.value.push(movementId);
  }
};

useHotkey(["Escape"], () => {
  if (selectedMovements.value.length > 0) {
    selectedMovements.value = [];
  }
});

useHotkey(
  (e) => e.key === "a" && (e.metaKey || e.ctrlKey),
  () => {
    selectedMovements.value = movementsFiltered.value.map((m) => m.id);
  },
);
</script>

<template>
  <div class="flex flex-1 flex-col min-h-0 min-w-0">
    <MovementsFilters :view-id="viewId" :movements="movementsFiltered" />

    <div
      v-if="movementsFiltered.length !== 0"
      class="flex-1 flex flex-col sm:min-w-[575px] overflow-x-hidden"
    >
      <template v-if="grouping">
        <RecycleScroller
          v-slot="{ item }"
          :items="movementsWithGroups"
          :item-size="40"
          key-field="id"
          class="pb-40"
        >
          <div
            v-if="item.itemType === 'group'"
            class="bg-primary-800 h-10 flex items-center gap-2 pl-5 sm:pl-7 border-b flex-shrink-0"
          >
            <i class="mdi mdi-calendar-blank text-primary-100 mdi-16px" />
            <div class="text-sm font-medium">
              {{ periodFormatter(item.month, item.year) }}
            </div>
            <div class="flex-1" />
          </div>
          <MovementLine
            v-else
            :movement="item"
            :is-movement-selected="selectedMovements.includes(item.id)"
            @select-movement="selectMovement(item.id)"
            @click.prevent="handleMovementClick(item.id)"
          />
        </RecycleScroller>
      </template>
      <RecycleScroller
        v-else
        v-slot="{ item }"
        :items="movementsSorted"
        :item-size="40"
        key-field="id"
        class="pb-40"
      >
        <MovementLine
          :movement="item"
          :is-movement-selected="selectedMovements.includes(item.id)"
          @select-movement="selectMovement(item.id)"
          @click.prevent="handleMovementClick(item.id)"
        />
      </RecycleScroller>
    </div>
    <div v-else class="flex flex-1 items-center justify-center overflow-hidden">
      <div class="text-primary-600">No movement found</div>
    </div>
  </div>

  <MovementsActions
    :selected-movements="selectedMovements"
    @clear-selection="selectedMovements = []"
  />
</template>
