// apps/ui-react/src/components/movements/movement.tsx
import type { Movement } from "@maille/core/movements";
import { useHotkey } from "@tanstack/react-hotkeys";
import { useRouter } from "@tanstack/react-router";
import _ from "lodash";
import { ChevronRight, MoreVertical } from "lucide-react";
import * as React from "react";

import { AccountLabel } from "@/components/accounts/account-label";
import { AddActivityButton } from "@/components/activities/add-activity-button";
import { AmountInput } from "@/components/ui/amount-input";
import { Button } from "@/components/ui/button";
import { DatePicker } from "@/components/ui/date-picker";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { getCurrencyFormatter, cn } from "@/lib/utils";
import {
  deleteMovementMutation,
  updateMovementMutation,
} from "@/mutations/movements";
import { useActivities } from "@/stores/activities";
import { useMovements } from "@/stores/movements";
import { useSync } from "@/stores/sync";

interface MovementProps {
  movementId: string;
  onClose: () => void;
}

export function Movement({ movementId, onClose }: MovementProps) {
  const router = useRouter();
  const mainElement = React.useRef<HTMLDivElement>(null);
  const [showMovement, setShowMovement] = React.useState(true);
  const [showProperties, setShowProperties] = React.useState(true);
  const [showActivities, setShowActivities] = React.useState(true);

  const movement = useMovements((state) => state.getMovementById(movementId));

  const activities = useActivities((state) => state.activities);

  const movementActivities = React.useMemo(() => {
    if (!movement) return [];
    return movement.activities
      .map((ma) => ({
        ...ma,
        activity: activities.find((a) => a.id === ma.activity),
      }))
      .filter((ma) => ma.activity !== undefined);
  }, [movement, activities]);

  // Animation logic
  React.useEffect(() => {
    if (movementId) {
      if (showMovement) return;

      setShowMovement(true);
    } else {
      // Exit animation
      setTimeout(() => {
        setShowMovement(false);
      }, 100);
    }
  }, [movementId]);

  const deleteMovement = useMovements((state) => state.deleteMovement);
  const updateMovement = useMovements((state) => state.updateMovement);
  const mutate = useSync((state) => state.mutate);

  const handleMovementMenuClick = (event: string) => {
    if (!movement) return;

    if (event === "delete") {
      const movementData = _.cloneDeep(movement);
      deleteMovement(movementId);

      mutate({
        name: "deleteMovement",
        mutation: deleteMovementMutation,
        variables: {
          id: movementId,
        },
        rollbackData: movementData,
      });

      onClose();
    }
  };

  const focusActivity = (activityNumber: number) => {
    router.navigate({
      to: "/activities/$id",
      params: { id: activityNumber.toString() },
    });
  };

  const handleUpdateMovement = (update: {
    date?: Date;
    amount?: number;
    account?: string;
    name?: string;
  }) => {
    if (!movement) return;

    const movementData = _.cloneDeep(movement);
    handleUpdateMovement(movementId, update);

    mutate({
      name: "updateMovement",
      mutation: updateMovementMutation,
      variables: {
        id: movementId,
        ...update,
        date: update.date?.toISOString().split("T")[0],
      },
      rollbackData: {
        ...movementData,
        date: movementData.date.toISOString().split("T")[0],
      },
    });
  };

  // Hotkeys
  useHotkey("Escape", () => {
    onClose();
  });

  if (!movement || !showMovement) return null;

  return (
    <div
      ref={mainElement}
      className="bg-primary-900 absolute top-0 left-0 flex h-full w-full max-w-full flex-col overflow-hidden rounded border shadow-xl @5xl:relative @5xl:w-[575px]"
    >
      <div className="flex h-14 w-full flex-shrink-0 items-center border-b px-4 sm:px-6">
        <Button
          type="button"
          variant="ghost"
          size="icon"
          className="mr-4 ml-8 h-8 w-6 lg:ml-0"
          onClick={onClose}
        >
          <ChevronRight className="h-6 w-6 transition hover:text-white" />
        </Button>
        <div className="text-sm font-medium text-white">Movement</div>

        <div className="flex-1" />
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon" className="mr-2 sm:mr-0">
              <MoreVertical className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuItem
              onSelect={() => handleMovementMenuClick("delete")}
            >
              <div className="flex items-center gap-2">
                <i
                  className="mdi mdi-delete text-destructive"
                  aria-hidden="true"
                />
                <span>Delete</span>
              </div>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      <div className="mb-4 flex items-center px-4 pt-6 sm:px-8">
        <div className="flex">
          <div className="text-primary-500 bg-primary-700 -mx-2 flex h-8 items-center rounded border px-2.5 text-sm">
            <AccountLabel accountId={movement.account} />
          </div>
        </div>
      </div>

      <div className="min-w-0 border-b px-4 pb-6 text-lg font-bold text-white sm:px-8">
        {movement.name}
      </div>

      <div className="border-b px-4 py-6 sm:px-8">
        <div className="flex">
          <button
            className="-ml-2 flex h-7 items-center gap-2 rounded px-2 text-sm font-medium hover:text-white"
            onClick={() => setShowProperties(!showProperties)}
          >
            <span>Properties</span>
            <ChevronRight
              className={`h-4 w-4 transition-transform ${showProperties ? "rotate-90" : ""}`}
            />
          </button>
        </div>

        {showProperties && (
          <div className="space-y-4 pt-4">
            <div className="mb-2 flex items-center justify-between">
              <div className="text-sm">Date</div>
              <div className="flex-1" />
              <DatePicker
                value={movement.date}
                onChange={(date) => updateMovement({ date })}
                className="h-8 text-sm font-medium text-white"
              />
            </div>

            <div className="flex items-center justify-between">
              <div className="text-sm">Amount</div>
              <div className="flex-1" />
              <AmountInput
                value={movement.amount}
                onChange={(amount) => updateMovement({ amount })}
                className="h-8 text-sm font-medium text-white"
              />
            </div>
          </div>
        )}
      </div>

      <div className="px-4 py-6 sm:px-8">
        <div className="flex">
          <button
            className="text-primary-100 -ml-2 flex h-7 items-center gap-2 rounded px-2 text-sm font-medium hover:text-white"
            onClick={() => setShowActivities(!showActivities)}
          >
            <span>Activities linked</span>
            <ChevronRight
              className={`h-4 w-4 transition-transform ${showActivities ? "rotate-90" : ""}`}
            />
          </button>

          <div className="flex-1" />

          {showActivities && (
            <AddActivityButton
              movement={movement}
              className="-mr-2"
              onCreate={focusActivity}
            />
          )}
        </div>

        {showActivities && (
          <div className="bg-primary-800 -mx-4 mt-4 mb-2 rounded border">
            {movementActivities.length === 0 ? (
              <div className="text-primary-300 flex items-center justify-center py-4 text-xs">
                No activity linked to this movement yet.
              </div>
            ) : (
              movementActivities.map((movementActivity, index) => (
                <div
                  key={movementActivity.id}
                  className={cn(
                    "hover:bg-primary-600/20 flex h-10 items-center justify-center px-4 text-sm",
                    index !== movementActivities.length - 1 && "border-b",
                  )}
                  onClick={() =>
                    focusActivity(movementActivity.activity!.number)
                  }
                >
                  <div className="text-primary-100 hidden w-8 shrink-0 sm:block">
                    #{movementActivity.activity!.number}
                  </div>
                  <div className="text-primary-100 ml-2 hidden w-20 shrink-0 sm:block">
                    {movementActivity.activity!.date.toLocaleDateString(
                      "fr-FR",
                    )}
                  </div>
                  <div className="text-primary-100 w-10 shrink-0 sm:hidden">
                    {movementActivity.activity!.date.toLocaleDateString(
                      "fr-FR",
                      {
                        day: "2-digit",
                        month: "2-digit",
                      },
                    )}
                  </div>

                  <div className="ml-1 overflow-hidden text-ellipsis whitespace-nowrap text-white">
                    {movementActivity.activity!.name}
                  </div>
                  <div className="flex-1" />
                  <div className="w-20 text-right font-mono whitespace-nowrap text-white">
                    {getCurrencyFormatter().format(movementActivity.amount)}
                  </div>
                </div>
              ))
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// apps/ui/src/containers/movements/Movement.vue
<script lang="ts" setup>
import dayjs from "dayjs";
import { computed, ref, watch } from "vue";
import { storeToRefs } from "pinia";
import { useMotion } from "@vueuse/motion";

import AccountLabel from "@/components/AccountLabel.vue";

import AddActivityButton from "@/containers/activities/AddActivityButton.vue";

import { useMovementsStore } from "@/stores/movements";
import { useActivitiesStore } from "@/stores/activities";

import type { Movement } from "@maille/core/movements";

import { getCurrencyFormatter } from "@/utils/currency";
import type { UUID } from "crypto";
import { useEventsStore } from "@/stores/events";
import {
  deleteMovementMutation,
  updateMovementMutation,
} from "@/mutations/movements";
import _ from "lodash";
import { useRouter } from "vue-router";
import { useHotkey } from "@/hooks/use-hotkey";

const movementsStore = useMovementsStore();
const { focusedMovement } = storeToRefs(movementsStore);

const activitiesStore = useActivitiesStore();

const mainElement = ref<HTMLElement>();
const showMovement = ref(focusedMovement.value !== null);
const showProperties = ref(true);
const showActivities = ref(true);

const router = useRouter();

watch(focusedMovement, () => {
  if (focusedMovement.value !== null) {
    if (showMovement.value) return;

    showMovement.value = true;
    useMotion(mainElement, {
      initial: {
        marginLeft: window.innerWidth > 640 ? -576 : 0,
        x: 576,
      },
      enter: {
        marginLeft: 0,
        x: 0,
        transition: {
          type: "spring",
          stiffness: 250,
          damping: 25,
          mass: 0.5,
        },
      },
    });
  } else {
    useMotion(mainElement, {
      initial: {
        marginLeft: 0,
        x: 0,
      },
      enter: {
        marginLeft: window.innerWidth > 640 ? -576 : 0,
        x: 576,
        transition: {
          type: "spring",
          stiffness: 250,
          damping: 25,
          mass: 0.5,
        },
      },
    });

    setTimeout(() => {
      showMovement.value = false;
    }, 100);
  }
});

const movement = computed<Movement | undefined>(() => {
  if (focusedMovement.value === null) return;
  return movementsStore.getMovementById(focusedMovement.value);
});

const movementActivities = computed(() => {
  if (movement.value === undefined) return;
  return movement.value.activities.map((ma) => ({
    ...ma,
    activity: activitiesStore.getActivityById(ma.activity)!,
  }));
});

const handleMovementMenuClick = (event: string) => {
  if (focusedMovement.value === null) return;
  else if (movement.value === undefined) return;

  if (event === "delete") {
    const movementData = _.cloneDeep(movement.value);
    movementsStore.deleteMovement(focusedMovement.value);

    eventsStore.sendEvent({
      name: "deleteMovement",
      mutation: deleteMovementMutation,
      variables: {
        id: focusedMovement.value,
      },
      rollbackData: movementData,
    });

    close();
  }
};

const focusActivity = (activityNumber: number) => {
  router.push({ name: "activities", params: { id: activityNumber } });
};

const close = () => {
  focusedMovement.value = null;
};

const eventsStore = useEventsStore();

const updateMovement = (update: {
  date?: dayjs.Dayjs;
  name?: string;
  account?: UUID;
  amount?: number;
}) => {
  if (!movement.value) return;

  const movementData = _.cloneDeep(movement.value);
  movementsStore.updateMovement(movement.value!.id, update);

  eventsStore.sendEvent({
    name: "updateMovement",
    mutation: updateMovementMutation,
    variables: {
      id: movement.value.id,
      ...update,
      date: update.date?.format("YYYY-MM-DD"),
    },
    rollbackData: {
      ...movementData,
      date: movementData.date.format("YYYY-MM-DD"),
    },
  });
};

useHotkey(["Escape"], () => {
  close();
});
</script>

<template>
  <div
    v-if="showMovement"
    ref="mainElement"
    class="absolute top-0 left-0 sm:relative flex flex-col w-full sm:w-[575px] max-w-full h-full overflow-hidden border bg-primary-900 shadow-xl rounded"
  >
    <template v-if="movement">
      <div
        class="flex items-center px-4 sm:px-6 border-b w-full flex-shrink-0 h-14"
      >
        <button
          type="button"
          class="inline-flex items-center justify-center w-6 h-8 ml-8 sm:ml-0 mr-4"
          @click="close"
        >
          <i
            class="mdi mdi-chevron-right mdi-24px transition hover:text-white"
          />
        </button>
        <div class="text-white text-sm font-medium">Movement</div>

        <div class="flex-1" />
        <TMenu
          class="mr-2 sm:mr-0"
          :items="[{ value: 'delete', text: 'Delete', icon: 'delete' }]"
          @click:item="handleMovementMenuClick($event)"
        />
      </div>

      <div class="px-4 sm:px-8 pt-6 mb-4 flex items-center">
        <div class="flex">
          <div
            class="text-sm border px-2.5 h-8 flex items-center text-primary-500 rounded -mx-2 bg-primary-700"
          >
            <AccountLabel :account-id="movement.account" />
          </div>
        </div>
      </div>

      <div
        class="px-4 sm:px-8 pb-6 border-b text-white min-w-0 font-bold text-lg"
      >
        {{ movement.name }}
      </div>

      <div class="py-6 px-4 sm:px-8 border-b">
        <div class="flex">
          <div
            class="-ml-2 text-sm font-medium px-2 rounded h-7 hover:text-white flex items-center"
            @click="showProperties = !showProperties"
          >
            Properties
            <i
              class="mdi ml-2"
              :class="showProperties ? 'mdi-menu-down' : 'mdi-menu-up'"
            />
          </div>
        </div>

        <div v-show="showProperties" class="pt-4">
          <div class="flex items-center justify-between mb-2">
            <div class="text-sm">Date</div>

            <TDatePicker
              :model-value="movement.date"
              borderless
              class="h-8 text-sm font-medium text-white"
              @update:model-value="updateMovement({ date: $event })"
            />
          </div>

          <div class="flex items-center justify-between">
            <div class="text-sm">Amount</div>

            <TAmountInput
              :model-value="movement.amount"
              borderless
              class="h-8 text-sm font-medium text-white"
              @update:model-value="updateMovement({ amount: $event })"
            />
          </div>
        </div>
      </div>

      <div class="py-6 px-4 sm:px-8">
        <div class="flex">
          <div
            class="-ml-2 text-sm font-medium text-primary-100 px-2 rounded h-7 hover:text-white flex items-center"
            @click="showActivities = !showActivities"
          >
            Activities linked
            <i
              class="mdi ml-2"
              :class="showActivities ? 'mdi-menu-down' : 'mdi-menu-up'"
            />
          </div>

          <div class="flex-1" />

          <AddActivityButton
            v-if="showActivities"
            :movement="movement"
            class="-mr-2"
            @create="focusActivity"
          />
        </div>

        <div
          v-show="showActivities"
          class="mt-4 mb-2 bg-primary-800 -mx-4 rounded border"
        >
          <template
            v-for="(movementActivity, index) in movementActivities"
            :key="movementActivity.id"
          >
            <div
              class="h-10 flex items-center justify-center text-sm px-4 hover:bg-primary-600/20"
              :class="[index !== movementActivities!.length - 1 && 'border-b']"
              @click="focusActivity(movementActivity.activity.number)"
            >
              <div class="w-8 text-primary-100 hidden sm:block shrink-0">
                #{{ movementActivity.activity.number }}
              </div>
              <div class="hidden sm:block text-primary-100 w-20 shrink-0 ml-2">
                {{ dayjs(movementActivity.activity.date).format("DD/MM/YYYY") }}
              </div>
              <div class="sm:hidden text-primary-100 w-10 shrink-0">
                {{ dayjs(movementActivity.activity.date).format("DD/MM") }}
              </div>

              <div
                class="ml-1 text-white text-ellipsis overflow-hidden whitespace-nowrap"
              >
                {{ movementActivity.activity.name }}
              </div>
              <div class="flex-1" />
              <div
                class="w-20 whitespace-nowrap text-right text-white font-mono"
              >
                {{ getCurrencyFormatter().format(movementActivity.amount) }}
              </div>
            </div>
          </template>

          <div
            v-if="movementActivities!.length === 0"
            class="flex items-center justify-center text-primary-300 text-xs py-4"
          >
            No activity linked to this movement yet.
          </div>
        </div>
      </div>
    </template>
  </div>
</template>
