// apps/ui/src/containers/movements/MovementLine.vue
<script lang="ts" setup>
import dayjs from "dayjs";
import { storeToRefs } from "pinia";

import AccountLabel from "@/components/AccountLabel.vue";

import { useMovementsStore } from "@/stores/movements";

import type { Movement } from "@maille/core/movements";

import { getCurrencyFormatter } from "@/utils/currency";

const props = defineProps<{
  movement: Movement;
}>();

const movementsStore = useMovementsStore();
const { focusedMovement } = storeToRefs(movementsStore);
</script>

<template>
  <div
    class="h-10 flex items-center gap-2 pr-2 sm:pr-6 border-b text-sm flex-shrink-0 transition-colors"
    :class="
      focusedMovement === movement.id
        ? 'bg-primary-800/50 border-l-4 border-l-primary-400 pl-3 sm:pl-1'
        : 'hover:bg-primary-800/50 pl-4 sm:pl-2'
    "
  >
    <div class="hidden sm:block text-primary-100 w-20 shrink-0 ml-4">
      {{ dayjs(movement.date).format("DD/MM/YYYY") }}
    </div>
    <div class="sm:hidden text-primary-100 w-10 shrink-0">
      {{ dayjs(movement.date).format("DD/MM") }}
    </div>

    <i
      v-if="movement.status === 'incomplete'"
      class="mdi mdi-progress-helper text-lg text-orange-300"
    />
    <i v-else class="mdi mdi-check-circle-outline text-lg text-emerald-300" />
    <AccountLabel :account-id="movement.account" />

    <div
      class="ml-1 text-primary-100 text-ellipsis overflow-hidden whitespace-nowrap"
    >
      {{ movement.name }}
    </div>

    <div class="flex-1" />
    <div class="text-white text-right whitespace-nowrap font-mono">
      {{ getCurrencyFormatter().format(movement.amount) }}
    </div>
  </div>
</template>

// apps/ui-react/src/components/movements/movement-line.tsx
import type { Movement } from "@maille/core/movements";

import { Link } from "@tanstack/react-router";
import { format } from "date-fns";
import { CircleCheck, CircleDotDashed } from "lucide-react";

import { AccountLabel } from "@/components/accounts/account-label";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { useCurrencyFormatter } from "@/hooks/use-currency-formatter";
import { cn } from "@/lib/utils";

interface MovementLineProps {
  movement: Movement;
  selected: boolean;
  checked: boolean;
  onClick: () => void;
  onCheckedChange: (checked: boolean) => void;
}

export function MovementLine({
  movement,
  selected,
  checked,
  onClick,
  onCheckedChange,
}: MovementLineProps) {
  const currencyFormatter = useCurrencyFormatter();

  return (
    <div
      key={movement.id}
      className={cn(
        "group flex h-10 shrink-0 items-center gap-2 overflow-hidden border-b pr-2 text-sm transition-colors hover:bg-accent lg:pr-6",
        {
          "border-l-4 border-l-primary bg-accent pl-4.5": selected,
          "pl-5.5": !selected,
          "bg-primary/30 hover:bg-primary/40": checked,
        },
      )}
      onClick={onClick}
    >
      <Checkbox
        checked={checked}
        onCheckedChange={(checked) =>
          checked != "indeterminate" && onCheckedChange(checked)
        }
        onClick={(e) => e.stopPropagation()}
        className={cn(
          "mr-3.5 hidden opacity-0 transition-opacity group-hover:opacity-100 sm:flex",
          checked && "opacity-100",
        )}
      />

      <div
        className={cn(
          "size-2 shrink-0 rounded-lg",
          movement.amount > 0 ? "bg-green-400" : "bg-red-400",
        )}
      />

      <div className="mx-1 hidden w-12 shrink-0 text-muted-foreground lg:block">
        {format(movement.date, "dd EEE")}
      </div>
      <div className="w-10 shrink-0 text-muted-foreground lg:hidden">
        {format(movement.date, "dd EEEEE")}
      </div>

      {movement.status === "incomplete" ? (
        <CircleDotDashed className=" size-4 text-orange-300" />
      ) : (
        <CircleCheck className="size-4 text-indigo-300" />
      )}

      <div className="text-primary-100 overflow-hidden text-ellipsis whitespace-nowrap">
        {movement.name}
      </div>

      <div className="flex-1" />
      <Badge
        variant="outline"
        asChild
        className="mr-3 h-6 [a]:hover:bg-border/50"
        onClick={(e) => e.stopPropagation()}
      >
        <Link to={`/accounts/$id`} params={{ id: movement.account }}>
          <AccountLabel accountId={movement.account} />
        </Link>
      </Badge>
      <div className="text-right font-mono whitespace-nowrap text-white">
        {currencyFormatter.format(movement.amount)}
      </div>
    </div>
  );
}
