// apps/ui/src/containers/liabilities/ExportLiabilitiesButton.vue
<script setup lang="ts">
import { computed } from "vue";

import { stringify } from "csv-stringify/browser/esm/sync";

import { useViewsStore } from "@/stores/views";

import {
  verifyLiabilityFilter,
  type Liability,
} from "@maille/core/liabilities";

const props = defineProps<{
  viewId: string;
  liabilities: Liability[];
}>();

const liabilityView = computed(() =>
  useViewsStore().getLiabilityView(props.viewId),
);

const filteredLiabilities = computed(() => {
  return props.liabilities.filter((liability) => {
    if (liabilityView.value.filters.length === 0) return true;

    return liabilityView.value.filters
      .map((filter) => {
        return verifyLiabilityFilter(filter, liability);
      })
      .every((f) => f);
  });
});

const exportLiabilities = () => {
  const csvFile = stringify([
    ["id", "date", "name", "amount", "account"],
    ...filteredLiabilities.value.map((l) => [
      l.id,
      l.date.format("YYYY-MM-DD"),
      l.name,
      l.amount,
      l.account,
    ]),
  ]);

  const url = window.URL.createObjectURL(new Blob([csvFile]));
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", `liabilities_export.csv`);
  document.body.appendChild(link);
  link.click();
  link.remove();
};
</script>

<template>
  <TTooltip text="Export liabilities">
    <button
      type="button"
      class="inline-flex items-center justify-center transition text-primary-100 hover:text-white hover:border-primary-300 rounded h-7 w-7 border border-dashed"
      @click="exportLiabilities"
    >
      <i class="mdi mdi-download mt-0.5" />
    </button>
  </TTooltip>
</template>

// apps/ui-react/src/components/liabilities/export-liabilities-button.tsx
import * as React from "react";
import { useViews } from "@/stores/views";
import { verifyLiabilityFilter } from "@maille/core/liabilities";
import { stringify } from "csv-stringify/browser/esm/sync";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";

interface ExportLiabilitiesButtonProps {
  viewId: string;
  liabilities: any[]; // Replace with proper Liability type
  className?: string;
}

export function ExportLiabilitiesButton({
  viewId,
  liabilities,
  className,
}: ExportLiabilitiesButtonProps) {
  const liabilityView = useViews((state) => state.getLiabilityView(viewId));

  const filteredLiabilities = React.useMemo(() => {
    return liabilities.filter((liability) => {
      if (liabilityView.filters.length === 0) return true;

      return liabilityView.filters
        .map((filter) => {
          return verifyLiabilityFilter(filter, liability);
        })
        .every((f) => f);
    });
  }, [liabilities, liabilityView.filters]);

  const exportLiabilities = () => {
    const csvFile = stringify([
      ["id", "date", "name", "amount", "account"],
      ...filteredLiabilities.map((l) => [
        l.id,
        l.date.toISOString().split("T")[0], // Format date as YYYY-MM-DD
        l.name,
        l.amount,
        l.account,
      ]),
    ]);

    const url = window.URL.createObjectURL(new Blob([csvFile]));
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `liabilities_export.csv`);
    document.body.appendChild(link);
    link.click();
    link.remove();
  };

  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <Button variant="outline" size="icon" className={className} onClick={exportLiabilities}>
          <Download className="h-4 w-4" />
        </Button>
      </TooltipTrigger>
      <TooltipContent>
        <p>Export liabilities</p>
      </TooltipContent>
    </Tooltip>
  );
}
