// apps/ui/src/containers/liabilities/LiabilityLine.vue
<script lang="ts" setup>
import dayjs from "dayjs";
import AccountLabel from "@/components/AccountLabel.vue";
import { getCurrencyFormatter } from "@/utils/currency";
import type { Liability } from "@maille/core/liabilities";
import { useRouter } from "vue-router";
import { useActivitiesStore } from "@/stores/activities";
import { computed } from "vue";

const router = useRouter();

const activitiesStore = useActivitiesStore();

const props = defineProps<{
  liability: Liability;
}>();

const activityLinked = computed(() => {
  if (!props.liability.activity) return null;
  return activitiesStore.getActivityById(props.liability.activity);
});

const goToActivity = () => {
  if (!activityLinked.value) return;
  router.push({
    name: "activities",
    params: { id: activityLinked.value.number },
  });
};
</script>

<template>
  <div
    class="h-10 flex items-center gap-2 pr-2 sm:pr-6 border-b text-sm flex-shrink-0 transition-colors hover:bg-primary-800/20 pl-4 sm:pl-2"
    @click="goToActivity"
  >
    <div class="hidden sm:block text-primary-100 w-20 shrink-0 ml-4">
      {{ dayjs(liability.date).format("DD/MM/YYYY") }}
    </div>
    <div class="sm:hidden text-primary-100 w-10 shrink-0">
      {{ dayjs(liability.date).format("DD/MM") }}
    </div>

    <AccountLabel :account-id="liability.account" />

    <div
      class="ml-1 text-primary-100 text-ellipsis overflow-hidden whitespace-nowrap"
    >
      {{ liability.name }}
    </div>

    <div class="flex-1" />
    <div class="text-white text-right whitespace-nowrap font-mono">
      {{ getCurrencyFormatter().format(liability.amount) }}
    </div>
  </div>
</template>

// apps/ui-react/src/components/liabilities/liability-line.tsx
import * as React from "react";
import { AccountLabel } from "@/components/accounts/account-label";
import { getCurrencyFormatter } from "@/lib/utils";
import type { Liability } from "@maille/core/liabilities";

interface LiabilityLineProps {
  liability: Liability;
  className?: string;
  onClick?: () => void;
}

export function LiabilityLine({ liability, className, onClick }: LiabilityLineProps) {
  const currencyFormatter = getCurrencyFormatter();

  const handleClick = () => {
    if (onClick) {
      onClick();
    }
  };

  const formattedDate = React.useMemo(() => {
    return liability.date.toLocaleDateString(undefined, {
      day: "2-digit",
      month: "2-digit",
      year: "numeric",
    });
  }, [liability.date]);

  const formattedDateMobile = React.useMemo(() => {
    return liability.date.toLocaleDateString(undefined, {
      day: "2-digit",
      month: "2-digit",
    });
  }, [liability.date]);

  return (
    <div
      className={`hover:bg-primary-800/20 flex h-10 flex-shrink-0 items-center gap-2 border-b pr-2 pl-4 text-sm transition-colors sm:pr-6 sm:pl-2 ${className || ""}`}
      onClick={handleClick}
    >
      <div className="text-primary-100 ml-4 hidden w-20 shrink-0 sm:block">{formattedDate}</div>
      <div className="text-primary-100 w-10 shrink-0 sm:hidden">{formattedDateMobile}</div>

      <AccountLabel accountId={liability.account} />

      <div className="text-primary-100 ml-1 overflow-hidden text-ellipsis whitespace-nowrap">
        {liability.name}
      </div>

      <div className="flex-1" />
      <div className="text-right font-mono whitespace-nowrap text-white">
        {currencyFormatter.format(liability.amount)}
      </div>
    </div>
  );
}
