// apps/ui/src/containers/liabilities/filters/FilterLiabilitiesButton.vue
<script setup lang="ts">
import { computed } from "vue";

import { useViewsStore } from "@/stores/views";

import {
  LiabilityFilterFields,
  type LiabilityFilter,
} from "@maille/core/liabilities";

defineOptions({ inheritAttrs: false });

const props = defineProps<{
  viewId: string;
}>();

const viewsStore = useViewsStore();
const liabilityView = computed(() => viewsStore.getLiabilityView(props.viewId));

const selectField = (field: LiabilityFilter["field"]) => {
  liabilityView.value.filters.push({
    field: field,
    operator: undefined,
    value: undefined,
  } satisfies LiabilityFilter);
};
</script>

<template>
  <TSelect
    :model-value="null"
    :items="LiabilityFilterFields"
    item-value="value"
    @update:model-value="selectField"
  >
    <template #default="{ open }">
      <button
        class="flex items-center rounded w-7 justify-center sm:w-auto sm:px-2.5 text-left text-sm h-7 border border-dashed hover:border-primary-300 text-primary-100 hover:text-white transition-colors shrink-0"
        :class="{
          'border-primary-300 text-white': open,
        }"
        v-bind="$attrs"
      >
        <i class="mdi mdi-filter-plus" />
        <span class="truncate ml-2 hidden sm:inline"> Filter </span>
      </button>
    </template>

    <template #item="{ item, active }">
      <div class="flex items-center">
        <i class="mdi mt-0.5" :class="item.icon" />
        <span class="block truncate ml-3" :class="{ 'font-medium': active }">
          {{ item.text }}
        </span>
      </div>
    </template>
  </TSelect>
</template>

// apps/ui-react/src/components/liabilities/filters/filter-liabilities-button.tsx
import * as React from "react";
import { useStore } from "zustand";
import { viewsStore } from "@/stores/views";
import { LiabilityFilterFields, type LiabilityFilter } from "@maille/core/liabilities";
import { Button } from "@/components/ui/button";
import { Plus } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

interface FilterLiabilitiesButtonProps {
  viewId: string;
  className?: string;
}

export function FilterLiabilitiesButton({ viewId, className }: FilterLiabilitiesButtonProps) {
  const liabilityView = useStore(viewsStore, (state) => state.getLiabilityView(viewId));
  const [open, setOpen] = React.useState(false);

  const selectField = (field: LiabilityFilter["field"]) => {
    liabilityView.filters.push({
      field: field,
      operator: undefined,
      value: undefined,
    } as LiabilityFilter);
    setOpen(false);
  };

  return (
    <DropdownMenu open={open} onOpenChange={setOpen}>
      <DropdownMenuTrigger asChild>
        <Button
          variant="outline"
          size="sm"
          className={className}
        >
          <Plus className="h-4 w-4 mr-2" />
          <span>Filter</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-48">
        {LiabilityFilterFields.map((field) => (
          <DropdownMenuItem key={field.value} onSelect={() => selectField(field.value)}>
            <div className="flex items-center">
              <i className={`mdi mt-0.5 mr-2 ${field.icon}`} aria-hidden="true" />
              <span>{field.text}</span>
            </div>
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
