// apps/ui/src/components/liabilities/filters/LiabilityFilterValueMenu.vue
<script setup lang="ts">
import { ref, nextTick } from "vue";

import AccountSelect from "@/components/accounts/AccountSelect.vue";
import TSelect from "@/components/designSystem/TSelect.vue";
import TAmountInput from "@/components/designSystem/TAmountInput.vue";
import TTextField from "@/components/designSystem/TTextField.vue";

import { ActivityFilterDateValues } from "@maille/core/activities";
import type { LiabilityFilter } from "@maille/core/liabilities";

defineOptions({ inheritAttrs: false });

const props = defineProps<{
  modelValue: LiabilityFilter["value"] | undefined;
  field: LiabilityFilter["field"];
}>();
const emit = defineEmits(["update:model-value", "close"]);

const textValue = ref(props.modelValue);

const input = ref();

defineExpose({
  click: () => {
    if (input.value) {
      input.value.click();
    }
  },
});
</script>

<template>
  <template v-if="field === 'date'">
    <TSelect
      ref="input"
      v-slot="{ open, text }"
      :model-value="modelValue"
      :items="ActivityFilterDateValues.map((v) => ({ value: v, text: v }))"
      @update:model-value="emit('update:model-value', $event)"
      @close="emit('close')"
    >
      <button
        class="flex items-center px-2 text-sm h-7 text-primary-100 hover:text-white hover:bg-primary-700 transition-colors border-r min-w-[24px]"
        :class="{
          'bg-primary-700 text-white': open,
        }"
      >
        <span class="block truncate"> {{ text }} </span>
      </button>
    </TSelect>
  </template>
  <template v-else-if="field === 'amount'">
    <TAmountInput
      ref="input"
      borderless
      class="text-sm px-2 border-r h-7 hover:bg-primary-700 text-primary-100 hover:text-white"
      :model-value="modelValue as number"
      v-bind="$attrs"
      @update:model-value="emit('update:model-value', $event)"
      @close="emit('close')"
    />
  </template>
  <template v-else-if="field === 'name'">
    <TTextField
      ref="input"
      v-model="textValue as string | undefined"
      class="border-none min-w-0 bg-transparent hover:bg-primary-700"
      v-bind="$attrs"
      @keydown.enter="emit('update:model-value', textValue)"
      @blur="
        emit('update:model-value', textValue);
        nextTick(() => emit('close'));
      "
    />
  </template>
  <template v-if="field === 'account'">
    <AccountSelect
      ref="input"
      :model-value="modelValue"
      multiple
      borderless
      class="border-r hover:bg-primary-700"
      @update:model-value="emit('update:model-value', $event)"
      @close="emit('close')"
    />
  </template>
</template>

// apps/ui-react/src/components/liabilities/filters/liability-filter-value-menu.tsx
import { forwardRef, useImperativeHandle, useRef, useState } from "react";
import { ChevronDown } from "lucide-react";
import { ActivityFilterDateValues } from "@maille/core/activities";
import type { LiabilityFilter } from "@maille/core/liabilities";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { AccountSelect } from "@/components/accounts/account-select";

interface LiabilityFilterValueMenuProps {
  modelValue: LiabilityFilter["value"] | undefined;
  field: LiabilityFilter["field"];
  onUpdateModelValue: (value: LiabilityFilter["value"]) => void;
  onClose: () => void;
}

export const LiabilityFilterValueMenu = forwardRef<
  { click: () => void },
  LiabilityFilterValueMenuProps
>(({ modelValue, field, onUpdateModelValue, onClose }, ref) => {
  const inputRef = useRef<HTMLInputElement>(null);
  const selectRef = useRef<HTMLButtonElement>(null);
  const [textValue, setTextValue] = useState<string | undefined>(modelValue as string | undefined);
  const [open, setOpen] = useState(false);

  useImperativeHandle(ref, () => ({
    click: () => {
      if (inputRef.current) {
        inputRef.current.focus();
      } else if (selectRef.current) {
        selectRef.current.click();
      }
    },
  }));

  if (field === "date") {
    return (
      <Select
        value={modelValue as string | undefined}
        onValueChange={(value) => {
          onUpdateModelValue(value as LiabilityFilter["value"]);
        }}
        onOpenChange={(isOpen) => {
          setOpen(isOpen);
          if (!isOpen) {
            onClose();
          }
        }}
      >
        <SelectTrigger
          ref={selectRef}
          className={`flex items-center px-2 text-sm h-7 text-primary-100 hover:text-white hover:bg-primary-700 transition-colors border-r min-w-[24px] ${
            open ? "bg-primary-700 text-white" : ""
          }`}
        >
          <SelectValue placeholder="Date value" />
          <ChevronDown className="size-4 ml-1" />
        </SelectTrigger>
        <SelectContent className="bg-primary-800 border-primary-600">
          {ActivityFilterDateValues.map((value) => (
            <SelectItem key={value} value={value} className="text-primary-100 hover:bg-primary-700">
              {value}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    );
  } else if (field === "amount") {
    return (
      <Input
        ref={inputRef}
        type="number"
        value={modelValue as number | undefined}
        onChange={(e) => {
          const value = e.target.value;
          onUpdateModelValue(value === "" ? undefined : parseFloat(value));
        }}
        onBlur={() => onClose()}
        className="text-sm px-2 border-r h-7 hover:bg-primary-700 text-primary-100 hover:text-white bg-transparent border-none focus:ring-0"
      />
    );
  } else if (field === "name") {
    return (
      <Input
        ref={inputRef}
        value={textValue}
        onChange={(e) => setTextValue(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            onUpdateModelValue(textValue);
          }
        }}
        onBlur={() => {
          onUpdateModelValue(textValue);
          onClose();
        }}
        className="border-none min-w-0 bg-transparent hover:bg-primary-700 text-sm px-2 h-7 text-primary-100 hover:text-white focus:ring-0"
      />
    );
  } else if (field === "account") {
    return (
      <AccountSelect
        modelValue={modelValue && Array.isArray(modelValue) ? modelValue : []}
        onUpdateModelValue={(value) => {
          onUpdateModelValue(value);
        }}
        multiple
        borderless
        className="border-r hover:bg-primary-700"
      />
    );
  }

  return null;
});

LiabilityFilterValueMenu.displayName = "LiabilityFilterValueMenu";
