// apps/ui-react/src/components/settings/activity-type-section.tsx
import { useStore } from "zustand";
import { useState, useMemo } from "react";
import type { UUID } from "crypto";
import type { ActivityType } from "@maille/core/activities";
import { activitiesStore } from "@/stores/activities";
import { eventsStore } from "@/stores/events";
import { workspacesStore } from "@/stores/workspaces";
import {
  createActivityCategoryMutation,
  createActivitySubCategoryMutation,
  deleteActivityCategoryMutation,
  deleteActivitySubCategoryMutation,
} from "@/mutations/activities";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Plus, ChevronUp, ChevronDown, Trash2 } from "lucide-react";

// Define activity type colors and names similar to the Vue version
const ACTIVITY_TYPES_COLOR = {
  expense: "bg-red-300",
  revenue: "bg-green-300",
  investment: "bg-orange-400",
  neutral: "bg-stone-200",
};

const ACTIVITY_TYPES_NAME = {
  expense: "Expenses",
  revenue: "Revenues",
  investment: "Investments",
  neutral: "Neutral",
};

interface ActivityTypeSectionProps {
  activityType: ActivityType;
}

export function ActivityTypeSection({ activityType }: ActivityTypeSectionProps) {
  const {
    activityCategories,
    activitySubcategories,
    activities,
    addActivityCategory,
    addActivitySubcategory,
    deleteActivityCategory,
    deleteActivitySubcategory,
  } = useStore(activitiesStore, (state) => ({
    activityCategories: state.activityCategories,
    activitySubcategories: state.activitySubcategories,
    activities: state.activities,
    addActivityCategory: state.addActivityCategory,
    addActivitySubcategory: state.addActivitySubcategory,
    deleteActivityCategory: state.deleteActivityCategory,
    deleteActivitySubcategory: state.deleteActivitySubcategory,
  }));

  const sendEvent = useStore(eventsStore, (state) => state.sendEvent);
  const currentWorkspace = useStore(workspacesStore, (state) => state.currentWorkspace);

  const [expanded, setExpanded] = useState<UUID | null>(null);
  const [newCategory, setNewCategory] = useState({
    show: false,
    name: "",
  });
  const [newSubCategory, setNewSubCategory] = useState({
    show: false,
    name: "",
  });

  const toggleExpand = (categoryId: UUID) => {
    setExpanded(expanded === categoryId ? null : categoryId);
    setNewSubCategory({ show: false, name: "" });
  };

  const sortedCategories = useMemo(() => {
    return [...activityCategories]
      .filter((c) => c.type === activityType)
      .sort((a, b) => a.name.localeCompare(b.name));
  }, [activityCategories, activityType]);

  const cancelNewCategory = () => {
    setNewCategory({ show: false, name: "" });
  };

  const cancelNewSubCategory = () => {
    setNewSubCategory({ show: false, name: "" });
  };

  const getActivitiesLinkedToCategory = (categoryId: UUID) => {
    return activities.filter((a) => a.category === categoryId).length;
  };

  const getActivitiesLinkedToSubCategory = (subcategoryId: UUID) => {
    return activities.filter((a) => a.subcategory === subcategoryId).length;
  };

  const handleAddNewCategory = async () => {
    if (!newCategory.name) return;

    const category = addActivityCategory({
      name: newCategory.name,
      type: activityType,
    });

    sendEvent({
      name: "createActivityCategory",
      mutation: createActivityCategoryMutation,
      variables: {
        ...category,
        workspace: currentWorkspace?.id,
      },
      rollbackData: undefined,
    });

    cancelNewCategory();
  };

  const handleAddNewSubCategory = async () => {
    if (!newSubCategory.name || !expanded) return;

    const subcategory = addActivitySubcategory({
      name: newSubCategory.name,
      category: expanded,
    });

    sendEvent({
      name: "createActivitySubCategory",
      mutation: createActivitySubCategoryMutation,
      variables: {
        ...subcategory,
        workspace: currentWorkspace?.id,
      },
      rollbackData: undefined,
    });

    cancelNewSubCategory();
  };

  const handleDeleteCategory = async (categoryId: UUID) => {
    const categoryActivities = activities.filter((a) => a.category === categoryId).map((a) => a.id);
    const categoryActivitiesSubcategories = activities
      .filter((a) => a.category === categoryId)
      .map((a) => a.subcategory);
    const category = activityCategories.find((c) => c.id === categoryId);
    if (!category) return;

    deleteActivityCategory(categoryId);

    sendEvent({
      name: "deleteActivityCategory",
      mutation: deleteActivityCategoryMutation,
      variables: { id: category.id },
      rollbackData: {
        category: category,
        activities: categoryActivities,
        activitiesSubcategories: categoryActivitiesSubcategories.reduce(
          (acc, sc) => {
            if (sc) acc[sc] = sc;
            return acc;
          },
          {} as Record<UUID, UUID>,
        ),
      },
    });
  };

  const handleDeleteSubCategory = async (subcategoryId: UUID) => {
    const subcategoryActivities = activities
      .filter((a) => a.subcategory === subcategoryId)
      .map((a) => a.id);
    const subcategory = activitySubcategories.find((c) => c.id === subcategoryId);
    if (!subcategory) return;

    deleteActivitySubcategory(subcategoryId);

    sendEvent({
      name: "deleteActivitySubCategory",
      mutation: deleteActivitySubCategoryMutation,
      variables: { id: subcategory.id },
      rollbackData: {
        subcategory: subcategory,
        activities: subcategoryActivities,
      },
    });
  };

  return (
    <div className="pb-10">
      <div className="mb-2 flex items-center px-2">
        <div
          className={`mr-2 size-3 shrink-0 rounded sm:mr-3 ${ACTIVITY_TYPES_COLOR[activityType]}`}
        />
        <div className="text-primary-400 text-sm font-medium">
          {ACTIVITY_TYPES_NAME[activityType]}
        </div>

        <div className="flex-1" />
        <Button
          type="button"
          variant="ghost"
          size="icon"
          className="h-8 w-8"
          onClick={() => setNewCategory({ show: true, name: "" })}
        >
          <Plus className="text-primary-500 h-4 w-4" />
        </Button>
      </div>

      {newCategory.show && (
        <div className="bg-primary-900 my-2 flex h-12 w-full items-center rounded border px-4">
          <Input
            value={newCategory.name}
            onChange={(e) => setNewCategory({ ...newCategory, name: e.target.value })}
            placeholder="Name"
            autoFocus
            className="flex-1 border-none bg-transparent focus:ring-0 focus:outline-none"
          />

          <div className="flex-1" />
          <Button variant="outline" className="mr-2" onClick={cancelNewCategory}>
            Cancel
          </Button>
          <Button onClick={handleAddNewCategory}>Save</Button>
        </div>
      )}

      {sortedCategories.map((category) => (
        <div key={category.id} className="group my-2 w-full rounded border px-2">
          <div className="flex h-10 w-full items-center px-2">
            <div className="text-primary-200 text-sm font-medium">{category.name}</div>
            <div className="text-primary-600 ml-1 text-sm">
              · {getActivitiesLinkedToCategory(category.id)} activities
            </div>

            <div className="flex-1" />

            <AlertDialog>
              <AlertDialogTrigger asChild>
                <button className="mx-1">
                  <Trash2 className="text-primary-700 hover:text-primary-300 h-4 w-4" />
                </button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>Delete Category</AlertDialogTitle>
                  <AlertDialogDescription>
                    Are you sure you want to delete this category? All activities linked will lose
                    this category and all subcategories will be deleted as well.
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>Cancel</AlertDialogCancel>
                  <AlertDialogAction onClick={() => handleDeleteCategory(category.id)}>
                    Delete
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>

            <button className="ml-2" onClick={() => toggleExpand(category.id)}>
              {expanded === category.id ? (
                <ChevronUp className="text-primary-500 hover:text-primary-300 h-4 w-4" />
              ) : (
                <ChevronDown className="text-primary-500 hover:text-primary-300 h-4 w-4" />
              )}
            </button>
          </div>

          {expanded === category.id && (
            <div className="border-t py-4">
              <div className="mb-2 flex items-center px-2">
                <div className="text-primary-600 text-xs font-medium">Subcategories</div>
                <div className="flex-1" />
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  className="h-5 w-5"
                  onClick={() => setNewSubCategory({ show: true, name: "" })}
                >
                  <Plus className="text-primary-500 h-3 w-3" />
                </Button>
              </div>

              {newSubCategory.show && (
                <div className="bg-primary-900 my-2 flex h-12 w-full items-center rounded border px-2">
                  <Input
                    value={newSubCategory.name}
                    onChange={(e) => setNewSubCategory({ ...newSubCategory, name: e.target.value })}
                    placeholder="Name"
                    autoFocus
                    className="flex-1 border-none bg-transparent focus:ring-0 focus:outline-none"
                  />

                  <div className="flex-1" />
                  <Button variant="outline" className="mr-2" onClick={cancelNewSubCategory}>
                    Cancel
                  </Button>
                  <Button onClick={handleAddNewSubCategory}>Save</Button>
                </div>
              )}

              {activitySubcategories.filter((sc) => sc.category === category.id).length === 0 && (
                <div className="text-primary-600 px-2 text-xs">
                  No subcategory for this category.
                </div>
              )}

              {activitySubcategories
                .filter((sc) => sc.category === category.id)
                .map((subcategory) => (
                  <div
                    key={subcategory.id}
                    className="bg-primary-950 my-2 flex h-10 w-full items-center rounded border px-2"
                  >
                    <div className="text-primary-400 text-sm font-medium">{subcategory.name}</div>
                    <div className="text-primary-600 ml-1 text-sm">
                      · {getActivitiesLinkedToSubCategory(subcategory.id)} activities
                    </div>

                    <div className="flex-1" />

                    <AlertDialog>
                      <AlertDialogTrigger asChild>
                        <button>
                          <Trash2 className="text-primary-700 hover:text-primary-300 mx-1 h-4 w-4" />
                        </button>
                      </AlertDialogTrigger>
                      <AlertDialogContent>
                        <AlertDialogHeader>
                          <AlertDialogTitle>Delete Subcategory</AlertDialogTitle>
                          <AlertDialogDescription>
                            Are you sure you want to delete this subcategory? All activities linked
                            will lose this subcategory.
                          </AlertDialogDescription>
                        </AlertDialogHeader>
                        <AlertDialogFooter>
                          <AlertDialogCancel>Cancel</AlertDialogCancel>
                          <AlertDialogAction
                            onClick={() => handleDeleteSubCategory(subcategory.id)}
                          >
                            Delete
                          </AlertDialogAction>
                        </AlertDialogFooter>
                      </AlertDialogContent>
                    </AlertDialog>
                  </div>
                ))}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}

// apps/ui/src/containers/settings/categories/ActivityTypeSection.vue
<script setup lang="ts">
import _ from "lodash";
import { storeToRefs } from "pinia";
import { computed, ref } from "vue";
import {
  ACTIVITY_TYPES_COLOR,
  ACTIVITY_TYPES_NAME,
  useActivitiesStore,
} from "@/stores/activities";
import type { ActivityType } from "@maille/core/activities";
import { useEventsStore } from "@/stores/events";
import {
  createActivityCategoryMutation,
  createActivitySubCategoryMutation,
  deleteActivityCategoryMutation,
  deleteActivitySubCategoryMutation,
} from "@/mutations/activities";
import type { UUID } from "crypto";

const activitiesStore = useActivitiesStore();
const { activities, categories, subcategories } = storeToRefs(activitiesStore);

const eventsStore = useEventsStore();

const props = defineProps<{ activityType: ActivityType }>();

const expanded = ref<UUID | null>(null);
const newCategory = ref({
  show: false,
  name: undefined as string | undefined,
});
const newSubCategory = ref({
  show: false,
  name: undefined as string | undefined,
});

const toggleExpand = (categoryId: UUID) => {
  if (expanded.value === categoryId) {
    expanded.value = null;
  } else {
    expanded.value = categoryId;
  }
  cancelNewSubCategory();
};

const sortedCategories = computed(() => {
  return _.orderBy(
    categories.value.filter((c) => c.type === props.activityType),
    ["name"],
  );
});

const cancelNewCategory = () => {
  newCategory.value.show = false;
  newCategory.value.name = undefined;
};

const cancelNewSubCategory = () => {
  newSubCategory.value.show = false;
  newSubCategory.value.name = undefined;
};

const addNewCategory = async () => {
  if (!newCategory.value.name) return;

  const category = activitiesStore.createCategory(
    newCategory.value.name,
    props.activityType,
    false,
  );

  eventsStore.sendEvent({
    name: "createActivityCategory",
    mutation: createActivityCategoryMutation,
    variables: {
      ...category,
      user: false,
    },
    rollbackData: undefined,
  });
  cancelNewCategory();
};

const addNewSubCategory = async () => {
  if (!newSubCategory.value.name) return;
  else if (expanded.value === null) return;

  const subcategory = activitiesStore.createSubCategory(
    newSubCategory.value.name,
    expanded.value,
    false,
  );

  eventsStore.sendEvent({
    name: "createActivitySubCategory",
    mutation: createActivitySubCategoryMutation,
    variables: {
      ...subcategory,
      user: false,
    },
    rollbackData: undefined,
  });
  cancelNewSubCategory();
};

const getActivitiesLinkedToCategory = (categoryId: UUID) => {
  return activities.value.filter((a) => a.category === categoryId).length;
};

const getActivitiesLinkedToSubCategory = (subcategoryId: UUID) => {
  return activities.value.filter((a) => a.subcategory === subcategoryId).length;
};

const deleteCategory = async (categoryId: UUID) => {
  const categoryActivities = activities.value
    .filter((a) => a.category === categoryId)
    .map((a) => a.id);
  const categoryActivitiesSubcategories = activities.value
    .filter((a) => a.category === categoryId)
    .map((a) => a.subcategory);
  const category = categories.value.find((c) => c.id === categoryId);
  if (!category) throw new Error("category not found");

  activitiesStore.deleteCategory(categoryId);

  eventsStore.sendEvent({
    name: "deleteActivityCategory",
    mutation: deleteActivityCategoryMutation,
    variables: { id: category.id },
    rollbackData: {
      category: category,
      activities: categoryActivities,
      activitiesSubcategories: categoryActivitiesSubcategories.reduce(
        (acc, sc) => {
          acc[sc!] = sc!;
          return acc;
        },
        {} as Record<UUID, UUID>,
      ),
    },
  });
};

const deleteSubCategory = async (subcategoryId: UUID) => {
  const subcategoryActivities = activities.value
    .filter((a) => a.subcategory === subcategoryId)
    .map((a) => a.id);
  const subcategory = subcategories.value.find((c) => c.id === subcategoryId);
  if (!subcategory) throw new Error("subcategory not found");

  activitiesStore.deleteSubCategory(subcategoryId);

  eventsStore.sendEvent({
    name: "deleteActivitySubCategory",
    mutation: deleteActivitySubCategoryMutation,
    variables: { id: subcategory.id },
    rollbackData: {
      subcategory: subcategory,
      activities: subcategoryActivities,
    },
  });
};
</script>

<template>
  <div class="pb-10">
    <div class="flex items-center mb-2 px-2">
      <div
        class="size-3 rounded mr-2 sm:mr-3 shrink-0"
        :class="`bg-${ACTIVITY_TYPES_COLOR[activityType]}-300`"
      />
      <div class="text-sm font-medium text-primary-400">
        {{ ACTIVITY_TYPES_NAME[activityType] }}
      </div>

      <div class="flex-1" />
      <button
        type="button"
        class="rounded hover:bg-primary-600 h-8 w-8 flex items-center justify-center group"
        @click="newCategory.show = true"
      >
        <i
          class="mdi mdi-plus text-primary-500 group-hover:text-primary-300 text-sm"
        />
      </button>
    </div>

    <div
      v-if="newCategory.show"
      class="w-full bg-primary-900 my-2 px-4 rounded h-12 flex items-center border"
    >
      <TTextField
        v-model="newCategory.name"
        placeholder="Name"
        autofocus
        dense
      />

      <div class="flex-1" />
      <TBtn outlined class="mr-2" @click="cancelNewCategory"> Cancel </TBtn>
      <TBtn @click="addNewCategory">Save</TBtn>
    </div>

    <div
      v-for="category in sortedCategories"
      :key="category.id"
      class="w-full border my-2 px-2 rounded group"
    >
      <div class="h-10 flex items-center w-full px-2">
        <div class="text-sm font-medium text-primary-200">
          {{ category.name }}
        </div>
        <div class="text-sm text-primary-600 ml-1">
          ·
          {{ getActivitiesLinkedToCategory(category.id) }}
          activities
        </div>

        <div class="flex-1" />

        <TDeleteConfirmation
          description="Are you sure you want to delete this category? All activities linked will loose this category and all subcategories will be deleted as well."
          @confirm="deleteCategory(category.id)"
        >
          <template #default="{ open }">
            <i
              class="mdi mdi-delete text-primary-700 hover:text-primary-300 text-sm mx-1 hidden group-hover:block"
              @click="open"
            />
          </template>
        </TDeleteConfirmation>

        <i
          class="mdi text-primary-500 hover:text-primary-300 text-sm ml-2"
          :class="
            expanded === category.id ? 'mdi-chevron-up' : 'mdi-chevron-down'
          "
          @click="toggleExpand(category.id)"
        />
      </div>

      <div v-if="expanded === category.id" class="border-t py-4">
        <div class="flex items-center mb-2 px-2">
          <div class="text-xs text-primary-600 font-medium">Subcategories</div>
          <div class="flex-1" />
          <button
            type="button"
            class="rounded hover:bg-primary-600 h-5 w-5 flex items-center justify-center group"
            @click="newSubCategory.show = true"
          >
            <i
              class="mdi mdi-plus text-primary-500 group-hover:text-primary-300 text-sm"
            />
          </button>
        </div>

        <div
          v-if="newSubCategory.show"
          class="w-full bg-primary-900 my-2 px-2 rounded h-12 flex items-center border"
        >
          <TTextField
            v-model="newSubCategory.name"
            placeholder="Name"
            autofocus
            dense
          />

          <div class="flex-1" />
          <TBtn outlined class="mr-2" @click="cancelNewSubCategory">
            Cancel
          </TBtn>
          <TBtn @click="addNewSubCategory">Save</TBtn>
        </div>
        <div
          v-else-if="
            subcategories.filter((sc) => sc.category === category.id).length ===
            0
          "
          class="text-xs text-primary-600 px-2"
        >
          No subcategory for this category.
        </div>

        <div
          v-for="subcategory in subcategories.filter(
            (sc) => sc.category === category.id,
          )"
          :key="subcategory.id"
          class="h-10 flex items-center w-full rounded bg-primary-950 px-2 my-2 border"
        >
          <div class="text-sm font-medium text-primary-400">
            {{ subcategory.name }}
          </div>
          <div class="text-sm text-primary-600 ml-1">
            ·
            {{ getActivitiesLinkedToSubCategory(subcategory.id) }}
            activities
          </div>

          <div class="flex-1" />

          <TDeleteConfirmation
            description="Are you sure you want to delete this subcategory? All activities linked will loose this subcategory."
            @confirm="deleteSubCategory(subcategory.id)"
          >
            <template #default="{ open }">
              <i
                class="mdi mdi-delete text-primary-700 hover:text-primary-300 text-sm mx-1"
                @click="open"
              />
            </template>
          </TDeleteConfirmation>
        </div>
      </div>
    </div>
  </div>
</template>
