// apps/ui/src/components/periods/PeriodLabel.vue
<script setup lang="ts">
import { usePeriodsStore } from "@/stores/periods";
import type { Period } from "@/types/periods";
import { computed } from "vue";

const props = defineProps<{
  period: Period;
}>();

const label = computed(() => usePeriodsStore().getPeriodLabel(props.period));

const chipClass = computed(() => {
  if (label.value === "Completed")
    return "bg-primary-100 text-primary-600 border";
  else if (label.value === "Current") return "bg-primary-400 text-white";
  return "bg-primary-100 text-primary-300 border";
});
</script>

<template>
  <span class="px-2.5 py-1 text-xs rounded" :class="chipClass">
    {{ label }}
  </span>
</template>

// apps/ui-react/src/components/periods/period-label.tsx
import { usePeriodsStore } from "@/stores/periods";
import type { Period } from "@/types/periods";
import { useMemo } from "react";

interface PeriodLabelProps {
  period: Period;
}

export function PeriodLabel({ period }: PeriodLabelProps) {
  const { getPeriodLabel } = usePeriodsStore();

  const label = useMemo(() => {
    return getPeriodLabel(period);
  }, [period, getPeriodLabel]);

  const chipClass = useMemo(() => {
    if (label === "Completed") {
      return "bg-primary-100 text-primary-600 border";
    } else if (label === "Current") {
      return "bg-primary-400 text-white";
    }
    return "bg-primary-100 text-primary-300 border";
  }, [label]);

  return <span className={`px-2.5 py-1 text-xs rounded ${chipClass}`}>{label}</span>;
}
