// apps/ui/src/components/activities/filters/ActivityFilter.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from "vue";

import ActivityFilterOperatorMenu from "@/components/activities/filters/ActivityFilterOperatorMenu.vue";
import ActivityFilterValueMenu from "@/components/activities/filters/ActivityFilterValueMenu.vue";

import {
  ActivityFilterFields,
  OperatorsWithoutValue,
  type ActivityFilter,
} from "@maille/core/activities";

const props = defineProps<{
  modelValue: ActivityFilter;
}>();
const emit = defineEmits(["update:model-value", "delete"]);

const operatorMenu = ref<InstanceType<typeof ActivityFilterOperatorMenu>>();
const valueMenu = ref<InstanceType<typeof ActivityFilterValueMenu>>();

onMounted(() => {
  if (props.modelValue.operator === undefined) {
    operatorMenu.value!.click();
  } else if (props.modelValue.value === undefined) {
    if (valueMenu.value) {
      valueMenu.value.click();
    }
  }
});

watch(
  () => props.modelValue.operator,
  () => {
    if (props.modelValue.value === undefined) {
      nextTick(() => {
        if (valueMenu.value) {
          valueMenu.value.click();
        }
      });
    }
  },
);

const handleCloseOperator = () => {
  if (props.modelValue.operator === undefined) {
    emit("delete");
  }
};

const handleCloseValue = () => {
  if (
    props.modelValue.value === undefined ||
    (Array.isArray(props.modelValue.value) &&
      props.modelValue.value.length === 0)
  ) {
    emit("delete");
  }
};

const activityFilterField = computed(
  () =>
    ActivityFilterFields.find((aff) => aff.value === props.modelValue.field)!,
);
</script>

<template>
  <div
    class="flex items-center rounded overflow-hidden h-7 border w-fit max-w-full bg-primary-800"
  >
    <div
      class="flex items-center px-2 text-sm h-7 text-white border-r font-medium"
    >
      <i class="mdi mt-0.5" :class="activityFilterField.icon" />
      <span class="ml-2 mr-1">
        {{ activityFilterField.text }}
      </span>
    </div>

    <ActivityFilterOperatorMenu
      ref="operatorMenu"
      :model-value="modelValue.operator"
      :field="modelValue.field"
      @update:model-value="
        emit('update:model-value', { ...modelValue, operator: $event })
      "
      @close="handleCloseOperator"
    />

    <ActivityFilterValueMenu
      v-if="
        modelValue.operator !== undefined &&
        !OperatorsWithoutValue.includes(modelValue.operator as any)
      "
      ref="valueMenu"
      :model-value="modelValue.value"
      :field="modelValue.field"
      @update:model-value="
        emit('update:model-value', { ...modelValue, value: $event })
      "
      @close="handleCloseValue"
    />

    <button
      class="flex items-center justify-center text-md w-7 h-7 hover:text-white hover:bg-primary-700 transition-colors shrink-0"
      @click="emit('delete')"
    >
      <i class="mdi mdi-close mt-0.5" />
    </button>
  </div>
</template>

// apps/ui-react/src/components/activities/filters/activity-filter.tsx
import { useEffect, useRef } from "react";
import {
  ActivityFilterFields,
  OperatorsWithoutValue,
  type ActivityFilter,
} from "@maille/core/activities";
import { X } from "lucide-react";
import { ActivityFilterOperatorMenu } from "./activity-filter-operator-menu";
import { ActivityFilterValueMenu } from "./activity-filter-value-menu";

interface ActivityFilterProps {
  modelValue: ActivityFilter;
  onUpdateModelValue: (value: ActivityFilter) => void;
  onDelete: () => void;
}

export function ActivityFilter({ modelValue, onUpdateModelValue, onDelete }: ActivityFilterProps) {
  const operatorMenuRef = useRef<{ click: () => void }>(null);
  const valueMenuRef = useRef<{ click: () => void }>(null);

  useEffect(() => {
    if (modelValue.operator === undefined) {
      operatorMenuRef.current?.click();
    } else if (modelValue.value === undefined) {
      if (valueMenuRef.current) {
        valueMenuRef.current.click();
      }
    }
  }, [modelValue]);

  useEffect(() => {
    if (modelValue.operator !== undefined && modelValue.value === undefined) {
      setTimeout(() => {
        if (valueMenuRef.current) {
          valueMenuRef.current.click();
        }
      }, 0);
    }
  }, [modelValue.operator]);

  const handleCloseOperator = () => {
    if (modelValue.operator === undefined) {
      onDelete();
    }
  };

  const handleCloseValue = () => {
    if (
      modelValue.value === undefined ||
      (Array.isArray(modelValue.value) && modelValue.value.length === 0)
    ) {
      onDelete();
    }
  };

  const activityFilterField = ActivityFilterFields.find((aff) => aff.value === modelValue.field);

  if (!activityFilterField) return null;

  const showValueMenu =
    modelValue.operator !== undefined &&
    !OperatorsWithoutValue.includes(modelValue.operator as any);

  return (
    <div className="bg-primary-800 flex h-7 w-fit max-w-full items-center overflow-hidden rounded border">
      <div className="flex h-7 items-center border-r px-2 text-sm font-medium text-white">
        <i className={`mdi mt-0.5 ${activityFilterField.icon}`} aria-hidden="true" />
        <span className="mr-1 ml-2">{activityFilterField.text}</span>
      </div>

      <ActivityFilterOperatorMenu
        ref={operatorMenuRef}
        modelValue={modelValue.operator}
        field={modelValue.field}
        onUpdateModelValue={(operator: any) => {
          onUpdateModelValue({ ...modelValue, operator });
        }}
        onClose={handleCloseOperator}
      />

      {showValueMenu && (
        <ActivityFilterValueMenu
          ref={valueMenuRef}
          modelValue={modelValue.value}
          field={modelValue.field}
          onUpdateModelValue={(value: any) => {
            onUpdateModelValue({ ...modelValue, value });
          }}
          onClose={handleCloseValue}
        />
      )}

      <button
        className="text-md hover:bg-primary-700 flex h-7 w-7 shrink-0 items-center justify-center transition-colors hover:text-white"
        onClick={onDelete}
        aria-label="Delete filter"
      >
        <X className="mt-0.5 size-4" />
      </button>
    </div>
  );
}
