// apps/ui-react/src/components/activities/activity-transactions.tsx
import { type Activity, type Transaction } from "@maille/core/activities";
import { Trash2 } from "lucide-react";

import { AccountSelect } from "@/components/accounts/account-select";
import { AmountInput } from "@/components/ui/amount-input";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { getCurrencyFormatter } from "@/lib/utils";
import {
  updateTransactionMutation,
  deleteTransactionMutation,
} from "@/mutations/activities";
import { useSync } from "@/stores/sync";

import { AddTransactionButton } from "./add-transaction-button";

interface ActivityTransactionsProps {
  activity: Activity;
}

export function ActivityTransactions({ activity }: ActivityTransactionsProps) {
  const mutate = useSync((state) => state.mutate);
  const currencyFormatter = getCurrencyFormatter();

  const transactionsSum = activity.transactions.reduce(
    (sum, t) => sum + t.amount,
    0,
  );

  const handleTransactionUpdate = (
    transaction: Transaction,
    updateData: Partial<Transaction>,
  ) => {
    const oldTransaction = { ...transaction };
    mutate({
      name: "updateTransaction",
      mutation: updateTransactionMutation,
      variables: {
        activityId: activity.id,
        id: transaction.id,
        ...updateData,
      },
      rollbackData: oldTransaction,
      events: [
        {
          type: "updateTransaction",
          payload: {
            activityId: activity.id,
            id: transaction.id,
            ...updateData,
          },
        },
      ],
    });
  };

  const handleTransactionDelete = (transaction: Transaction) => {
    mutate({
      name: "deleteTransaction",
      mutation: deleteTransactionMutation,
      variables: {
        activityId: activity.id,
        id: transaction.id,
      },
      rollbackData: transaction,
      events: [
        {
          type: "deleteTransaction",
          payload: {
            activityId: activity.id,
            id: transaction.id,
          },
        },
      ],
    });
  };

  return (
    <div className="border-b px-4 py-6 sm:px-8">
      <div className="flex items-center">
        <div className="text-sm font-medium ">Transactions</div>
        <div className="flex-1" />
        <div className="text-primary-100 mr-4 font-mono text-sm whitespace-nowrap">
          {currencyFormatter.format(transactionsSum)}
        </div>
        <AddTransactionButton activity={activity} />
      </div>

      <div className="bg-primary-800 mt-4 mb-2">
        {activity.transactions.length === 0 ? (
          <div className="text-primary-300 p-4 text-sm">
            No transaction added for this activity.
          </div>
        ) : (
          activity.transactions.map((transaction, index) => (
            <div
              key={transaction.id}
              className={`hover:bg-primary-700 flex h-10 items-center justify-center text-sm ${
                index !== activity.transactions.length - 1 && "border-b"
              }`}
            >
              <AccountSelect
                value={transaction.fromAccount}
                onChange={(account) =>
                  handleTransactionUpdate(transaction, {
                    fromAccount: account as string,
                  })
                }
              />
              <div className="text-primary-200 mx-2 text-center">to</div>
              <AccountSelect
                value={transaction.toAccount}
                onChange={(account) =>
                  handleTransactionUpdate(transaction, {
                    toAccount: account as string,
                  })
                }
              />

              <div className="flex-1" />

              <AmountInput
                value={transaction.amount}
                onChange={(amount) => {
                  console.log(amount);
                  handleTransactionUpdate(transaction, {
                    amount: amount || undefined,
                  });
                }}
                className="mr-1.5 w-24"
              />

              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="ghost" size="icon" className="h-8 w-8">
                    <span className="sr-only">Actions</span>
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      viewBox="0 0 24 24"
                      fill="currentColor"
                      className="text-primary-100"
                    >
                      <path d="M12 16a2 2 0 0 1 2 2a2 2 0 0 1-2 2a2 2 0 0 1-2-2a2 2 0 0 1 2-2m0-6a2 2 0 0 1 2 2a2 2 0 0 1-2 2a2 2 0 0 1-2-2a2 2 0 0 1 2-2m0-6a2 2 0 0 1 2 2a2 2 0 0 1-2 2a2 2 0 0 1-2-2a2 2 0 0 1 2-2" />
                    </svg>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent className="bg-primary-700 border-primary-600">
                  <DropdownMenuItem
                    onClick={() => handleTransactionDelete(transaction)}
                    className="focus:bg-primary-600 text-red-400 focus:text-red-300"
                  >
                    <Trash2 className="mr-2 h-4 w-4" />
                    <span>Delete</span>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          ))
        )}
      </div>
    </div>
  );
}

// apps/ui/src/containers/activities/ActivityTransactions.vue
<script setup lang="ts">
import { computed, ref } from "vue";

import type { Activity, Transaction } from "@maille/core/activities";

import AddTransactionButton from "@/containers/activities/AddTransactionButton.vue";

import AccountSelect from "@/components/accounts/AccountSelect.vue";
import TAmountInput from "@/components/designSystem/TAmountInput.vue";

import { getCurrencyFormatter } from "@/utils/currency";

import { useActivitiesStore } from "@/stores/activities";
import { useEventsStore } from "@/stores/events";
import {
  deleteTransactionMutation,
  updateTransactionMutation,
} from "@/mutations/activities";

const activitiesStore = useActivitiesStore();
const eventsStore = useEventsStore();

const props = defineProps<{
  activity: Activity;
}>();

const showTransactions = ref(true);

const transactionsSum = computed(() => {
  return props.activity.transactions.reduce((s, t) => s + t.amount, 0);
});

const handleTransactionUpdate = (
  transaction: Transaction,
  updateData: Partial<Transaction>,
) => {
  const oldTransaction = { ...transaction };
  activitiesStore.updateTransaction(
    props.activity.id,
    transaction.id,
    updateData,
  );

  eventsStore.sendEvent({
    name: "updateTransaction",
    mutation: updateTransactionMutation,
    variables: {
      activityId: props.activity.id,
      id: transaction.id,
      ...updateData,
    },
    rollbackData: oldTransaction,
  });
};

const handleTransactionMenuClick = (
  transaction: Transaction,
  event: string,
) => {
  if (event === "delete") {
    activitiesStore.deleteTransaction(props.activity.id, transaction.id);

    eventsStore.sendEvent({
      name: "deleteTransaction",
      mutation: deleteTransactionMutation,
      variables: {
        activityId: props.activity.id,
        id: transaction.id,
      },
      rollbackData: transaction,
    });
  }
};
</script>

<template>
  <div class="border-b py-6 px-4 sm:px-8">
    <div class="flex items-center">
      <div
        class="-ml-2 text-sm font-medium text-primary-100 px-2 rounded h-7 hover:text-white flex items-center"
        @click="showTransactions = !showTransactions"
      >
        Transactions
        <i
          class="mdi ml-2"
          :class="showTransactions ? 'mdi-menu-down' : 'mdi-menu-up'"
        />
      </div>

      <div class="flex-1" />

      <template v-if="showTransactions">
        <div
          v-if="transactionsSum !== undefined"
          class="text-sm whitespace-nowrap mr-4 text-primary-100 font-mono"
        >
          {{ getCurrencyFormatter().format(transactionsSum) }}
        </div>
        <AddTransactionButton :activity="activity" />
      </template>
    </div>

    <div
      v-show="showTransactions"
      class="mt-4 mb-2 bg-primary-800 -mx-4 rounded border"
    >
      <template
        v-for="(transaction, index) in activity.transactions"
        :key="transaction.id"
      >
        <div
          class="h-10 flex items-center justify-center text-sm hover:bg-primary-700 px-4"
          :class="[index !== activity.transactions.length - 1 && 'border-b']"
        >
          <AccountSelect
            :model-value="transaction.fromAccount"
            borderless
            class="pl-0"
            @update:model-value="
              (account) =>
                handleTransactionUpdate(transaction, {
                  fromAccount: account,
                })
            "
          />
          <div class="mx-2 text-center text-primary-600">to</div>
          <AccountSelect
            :model-value="transaction.toAccount"
            borderless
            @update:model-value="
              (account) =>
                handleTransactionUpdate(transaction, { toAccount: account })
            "
          />

          <div class="flex-1" />

          <TAmountInput
            :model-value="transaction.amount"
            borderless
            class="mr-4"
            @update:model-value="
              (amount) => handleTransactionUpdate(transaction, { amount })
            "
          />

          <TMenu
            :items="[{ value: 'delete', text: 'Delete', icon: 'delete' }]"
            @click:item="handleTransactionMenuClick(transaction, $event)"
          />
        </div>
      </template>
      <div
        v-if="activity.transactions!.length === 0"
        class="text-sm text-primary-300 p-4"
      >
        No transaction added for this activity.
      </div>
    </div>
  </div>
</template>
