// apps/ui-react/src/components/activities/activity-movements.tsx
import { type Activity } from "@maille/core/activities";
import { getCurrencyFormatter } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { ChevronDown, ChevronUp } from "lucide-react";
import { useState } from "react";
import { useStore } from "zustand";
import { movementsStore } from "@/stores/movements";
import { accountsStore } from "@/stores/accounts";
import { eventsStore } from "@/stores/events";
import {
  updateMovementActivityMutation,
  deleteMovementActivityMutation,
} from "@/mutations/movements";
import { LinkMovementButton } from "@/components/movements/link-movement-button";
import { AccountLabel } from "@/components/accounts/account-label";
import { AmountInput } from "@/components/ui/amount-input";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Trash2, RefreshCw, Edit2 } from "lucide-react";
import {
  getActivityMovementsReconciliated,
  getActivityMovementsReconciliatedByAccount,
} from "@maille/core/activities";

interface ActivityMovementsProps {
  activity: Activity;
}

export function ActivityMovements({ activity }: ActivityMovementsProps) {
  const currencyFormatter = getCurrencyFormatter();
  const [showMovements, setShowMovements] = useState(true);
  const accounts = useStore(accountsStore, (state) => state.accounts);

  const movementsReconciliatedByAccount = getActivityMovementsReconciliatedByAccount(
    activity.transactions,
    activity.movements,
    accounts,
    movementsStore.getState().getMovementById,
  );

  const isReconciled = getActivityMovementsReconciliated(
    activity.transactions,
    activity.movements,
    accounts,
    movementsStore.getState().getMovementById,
  );

  const handleMovementMenuClick = (
    movementWithLink: any, // TODO: Fix proper typing
    event: string,
  ) => {
    if (event === "unlink") {
      movementsStore
        .getState()
        .deleteMovementActivity(movementWithLink.id, movementWithLink.movementActivityId);

      eventsStore.getState().sendEvent({
        name: "deleteMovementActivity",
        mutation: deleteMovementActivityMutation,
        variables: {
          id: movementWithLink.movementActivityId,
        },
        rollbackData: {
          id: movementWithLink.movementActivityId,
          movement: movementWithLink.id,
          activity: activity.id,
          amount: movementWithLink.amount,
        },
      });
    } else if (event === "resetAmount") {
      movementsStore
        .getState()
        .updateMovementActivity(
          movementWithLink.id,
          movementWithLink.movementActivityId,
          movementWithLink.amount,
        );

      eventsStore.getState().sendEvent({
        name: "updateMovementActivity",
        mutation: updateMovementActivityMutation,
        variables: {
          id: movementWithLink.movementActivityId,
          amount: movementWithLink.amount,
        },
        rollbackData: {
          id: movementWithLink.movementActivityId,
          movement: movementWithLink.id,
          amount: movementWithLink.amount,
        },
      });
    }
  };

  const updateAmountLinked = (
    movementWithLink: any, // TODO: Fix proper typing
    newAmount: number,
  ) => {
    movementsStore
      .getState()
      .updateMovementActivity(movementWithLink.id, movementWithLink.movementActivityId, newAmount);

    eventsStore.getState().sendEvent({
      name: "updateMovementActivity",
      mutation: updateMovementActivityMutation,
      variables: {
        id: movementWithLink.movementActivityId,
        amount: newAmount,
      },
      rollbackData: {
        id: movementWithLink.movementActivityId,
        movement: movementWithLink.id,
        amount: movementWithLink.amount,
      },
    });
  };

  return (
    <div className="border-b px-4 py-6 sm:px-8">
      <div className="flex items-center">
        <button
          className="text-primary-100 flex h-7 w-full items-center rounded text-sm font-medium hover:text-white"
          onClick={() => setShowMovements(!showMovements)}
        >
          Movements
          {showMovements ? (
            <ChevronDown className="ml-2 h-4 w-4" />
          ) : (
            <ChevronUp className="ml-2 h-4 w-4" />
          )}
          <div className="flex-1" />
          {!isReconciled ? (
            <i className="px-1 text-xl text-orange-300">⚠️</i>
          ) : (
            <i className="px-1 text-xl text-emerald-400">✓</i>
          )}
        </button>
      </div>

      {showMovements && (
        <div className="mt-4">
          {movementsReconciliatedByAccount.length === 0 ? (
            <div className="text-primary-300 bg-primary-800 -mx-4 mt-4 rounded border p-4 text-sm sm:-mx-8">
              No movement needed for this activity.
            </div>
          ) : (
            movementsReconciliatedByAccount.map((movementsReconciliatedOfAccount) => (
              <div
                key={movementsReconciliatedOfAccount.account.toString()}
                className="bg-primary-800 -mx-4 mt-4 mb-2 rounded border py-4 sm:-mx-8"
              >
                <div className="flex items-center px-4">
                  <AccountLabel accountId={movementsReconciliatedOfAccount.account} />

                  <div className="flex-1" />

                  <div
                    className="mr-4 ml-3 font-mono text-sm font-medium whitespace-nowrap"
                    style={{
                      color: !movementsReconciliatedOfAccount.reconcilied ? "#f97316" : "#a5b4fc",
                    }}
                  >
                    {currencyFormatter.format(movementsReconciliatedOfAccount.movementTotal)}/
                    {currencyFormatter.format(movementsReconciliatedOfAccount.transactionTotal)}
                  </div>

                  <LinkMovementButton
                    activity={activity}
                    account={movementsReconciliatedOfAccount.account}
                  />
                </div>

                <div className="mt-4 mb-2">
                  {movementsReconciliatedOfAccount.movements.length === 0 ? (
                    <div className="text-primary-600 mt-4 px-4 text-sm">
                      No movement added for this account.
                    </div>
                  ) : (
                    movementsReconciliatedOfAccount.movements.map((movement) => (
                      <div key={movement.id}>
                        <hr className="border-t" />

                        <div className="hover:bg-primary-700 flex h-10 items-center justify-center px-4 text-sm">
                          <div className="text-primary-100 mr-4 hidden w-16 shrink-0 sm:block">
                            {movement.date.toLocaleDateString()}
                          </div>
                          <div className="text-primary-100 mr-2 w-10 shrink-0 sm:hidden">
                            {movement.date.toLocaleDateString(undefined, {
                              day: "2-digit",
                              month: "2-digit",
                            })}
                          </div>
                          <div className="ml-1 overflow-hidden text-ellipsis whitespace-nowrap text-white">
                            {movement.name}
                            {movement.amountLinked !== movement.amount && (
                              <span className="text-primary-100 ml-2 font-mono text-sm whitespace-nowrap">
                                ({currencyFormatter.format(movement.amount)})
                              </span>
                            )}
                          </div>

                          <div className="flex-1" />

                          <AmountInput
                            value={movement.amountLinked}
                            onChange={(amount) => updateAmountLinked(movement, amount)}
                            className="mr-4 w-24"
                          />

                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button variant="ghost" size="icon" className="h-8 w-8">
                                <span className="sr-only">Actions</span>
                                <svg
                                  xmlns="http://www.w3.org/2000/svg"
                                  width="16"
                                  height="16"
                                  viewBox="0 0 24 24"
                                  fill="currentColor"
                                  className="text-primary-100"
                                >
                                  <path d="M12 16a2 2 0 0 1 2 2a2 2 0 0 1-2 2a2 2 0 0 1-2-2a2 2 0 0 1 2-2m0-6a2 2 0 0 1 2 2a2 2 0 0 1-2 2a2 2 0 0 1-2-2a2 2 0 0 1 2-2m0-6a2 2 0 0 1 2 2a2 2 0 0 1-2 2a2 2 0 0 1-2-2a2 2 0 0 1 2-2" />
                                </svg>
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent className="bg-primary-700 border-primary-600">
                              <DropdownMenuItem
                                onClick={() => handleMovementMenuClick(movement, "editAmount")}
                                className="focus:bg-primary-600"
                              >
                                <Edit2 className="mr-2 h-4 w-4" />
                                <span>Modify amount linked</span>
                              </DropdownMenuItem>
                              <DropdownMenuItem
                                onClick={() => handleMovementMenuClick(movement, "resetAmount")}
                                className="focus:bg-primary-600"
                              >
                                <RefreshCw className="mr-2 h-4 w-4" />
                                <span>Reset amount linked</span>
                              </DropdownMenuItem>
                              <DropdownMenuItem
                                onClick={() => handleMovementMenuClick(movement, "unlink")}
                                className="focus:bg-primary-600 text-red-400 focus:text-red-300"
                              >
                                <Trash2 className="mr-2 h-4 w-4" />
                                <span>Unlink</span>
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </div>
                      </div>
                    ))
                  )}
                  <hr className="border-t" />
                </div>
              </div>
            ))
          )}
        </div>
      )}
    </div>
  );
}

// apps/ui/src/containers/activities/ActivityMovements.vue
<script setup lang="ts">
import dayjs from "dayjs";
import { computed, ref } from "vue";
import type { UUID } from "crypto";

import { useMovementsStore } from "@/stores/movements";

import LinkMovementButton from "@/containers/movements/LinkMovementButton.vue";

import AccountLabel from "@/components/AccountLabel.vue";
import TAmountInput from "@/components/designSystem/TAmountInput.vue";

import { getCurrencyFormatter } from "@/utils/currency";

import {
  getActivityMovementsReconciliated,
  getActivityMovementsReconciliatedByAccount,
} from "@maille/core/activities";
import type { MovementWithLink } from "@maille/core/movements";
import type { Activity } from "@maille/core/activities";
import { useAccountsStore } from "@/stores/accounts";
import { storeToRefs } from "pinia";
import { useEventsStore } from "@/stores/events";
import {
  deleteMovementActivityMutation,
  updateMovementActivityMutation,
} from "@/mutations/movements";

const movementsStore = useMovementsStore();
const eventsStore = useEventsStore();

const accountsStore = useAccountsStore();
const { accounts } = storeToRefs(accountsStore);

const props = defineProps<{ activity: Activity }>();

const showMovements = ref(true);
const movementsAmountInputs = ref<
  Record<UUID, InstanceType<typeof TAmountInput> | null>
>({});

const movementsReconciliatedByAccount = computed(() => {
  return getActivityMovementsReconciliatedByAccount(
    props.activity.transactions,
    props.activity.movements,
    accounts.value,
    movementsStore.getMovementById,
  );
});

const handleMovementMenuClick = (
  movementWithLink: MovementWithLink,
  event: string,
) => {
  if (event === "unlink") {
    movementsStore.deleteMovementActivity(
      movementWithLink.id,
      movementWithLink.movementActivityId,
    );

    eventsStore.sendEvent({
      name: "deleteMovementActivity",
      mutation: deleteMovementActivityMutation,
      variables: {
        id: movementWithLink.movementActivityId,
      },
      rollbackData: {
        id: movementWithLink.movementActivityId,
        movement: movementWithLink.id,
        activity: props.activity.id,
        amount: movementWithLink.amountLinked,
      },
    });
  } else if (event === "resetAmount") {
    movementsStore.updateMovementActivity(
      movementWithLink.id,
      movementWithLink.movementActivityId,
      movementWithLink.amount,
    );

    eventsStore.sendEvent({
      name: "updateMovementActivity",
      mutation: updateMovementActivityMutation,
      variables: {
        id: movementWithLink.movementActivityId,
        amount: movementWithLink.amount,
      },
      rollbackData: {
        id: movementWithLink.movementActivityId,
        movement: movementWithLink.id,
        amount: movementWithLink.amountLinked,
      },
    });
  } else if (event === "editAmount") {
    movementsAmountInputs.value[movementWithLink.movementActivityId]?.click();
  }
};

const updateAmountLinked = (
  movementWithLink: MovementWithLink,
  newAmount: number,
) => {
  movementsStore.updateMovementActivity(
    movementWithLink.id,
    movementWithLink.movementActivityId,
    newAmount,
  );

  eventsStore.sendEvent({
    name: "updateMovementActivity",
    mutation: updateMovementActivityMutation,
    variables: {
      id: movementWithLink.movementActivityId,
      amount: newAmount,
    },
    rollbackData: {
      id: movementWithLink.movementActivityId,
      movement: movementWithLink.id,
      amount: movementWithLink.amountLinked,
    },
  });
};
</script>
<template>
  <div class="border-b py-6 px-4 sm:px-8">
    <div class="flex items-center">
      <div
        class="text-sm font-medium text-primary-100 rounded h-7 hover:text-white flex items-center w-full"
        @click="showMovements = !showMovements"
      >
        Movements
        <i
          class="mdi ml-2"
          :class="showMovements ? 'mdi-menu-down' : 'mdi-menu-up'"
        />

        <div class="flex-1" />
        <i
          v-if="
            !getActivityMovementsReconciliated(
              activity.transactions,
              activity.movements,
              accounts,
              movementsStore.getMovementById,
            )
          "
          class="mdi mdi-progress-helper text-xl text-orange-300 px-1"
        />
        <i v-else class="mdi mdi-check-circle text-xl text-emerald-400 px-1" />
      </div>
    </div>

    <div v-show="showMovements">
      <div
        v-for="movementsReconciliatedOfAccount in movementsReconciliatedByAccount"
        :key="movementsReconciliatedOfAccount.account"
        class="mt-4 mb-2 border bg-primary-800 rounded py-4 -mx-3 sm:-mx-4"
      >
        <div class="flex items-center px-4">
          <AccountLabel
            :account-id="movementsReconciliatedOfAccount.account"
            class="text-sm ml-0.5"
          />

          <div class="flex-1" />

          <div
            class="whitespace-nowrap ml-3 font-medium text-sm mr-4 font-mono"
            :class="
              !movementsReconciliatedOfAccount.reconcilied
                ? 'text-red-400'
                : 'text-primary-200'
            "
          >
            {{
              getCurrencyFormatter().format(
                movementsReconciliatedOfAccount.movementTotal,
              )
            }}
            /
            {{
              getCurrencyFormatter().format(
                movementsReconciliatedOfAccount.transactionTotal,
              )
            }}
          </div>

          <LinkMovementButton
            :activity="activity"
            :account="movementsReconciliatedOfAccount.account"
          />
        </div>

        <div class="mt-4 mb-2">
          <template
            v-for="movement in movementsReconciliatedOfAccount.movements"
            :key="movement.id"
          >
            <hr class="border-t" />

            <div
              class="h-10 flex items-center justify-center text-sm hover:bg-primary-700 px-4"
            >
              <div class="hidden sm:block text-primary-100 w-16 mr-4 shrink-0">
                {{ dayjs(movement.date).format("DD/MM/YYYY") }}
              </div>
              <div
                class="ml-1 text-white text-ellipsis overflow-hidden whitespace-nowrap"
              >
                {{ movement.name }}
                <span
                  v-if="movement.amountLinked !== movement.amount"
                  class="text-sm text-primary-100 ml-2 whitespace-nowrap font-mono"
                >
                  ({{ getCurrencyFormatter().format(movement.amount) }})
                </span>
              </div>

              <div class="flex-1" />

              <TAmountInput
                :ref="
                  (el) =>
                    (movementsAmountInputs[movement.movementActivityId] =
                      el as InstanceType<typeof TAmountInput>)
                "
                :model-value="movement.amountLinked"
                borderless
                class="mr-4"
                @update:model-value="updateAmountLinked(movement, $event)"
              />

              <TMenu
                :items="[
                  {
                    value: 'editAmount',
                    text: 'Modify amount linked',
                    icon: 'book-edit',
                  },
                  {
                    value: 'resetAmount',
                    text: 'Reset amount linked',
                    icon: 'book-refresh',
                  },
                  {
                    value: 'unlink',
                    text: 'Unlink',
                    icon: 'link-variant-off',
                  },
                ]"
                @click:item="handleMovementMenuClick(movement, $event)"
              />
            </div>
          </template>
          <div
            v-if="movementsReconciliatedOfAccount.movements.length === 0"
            class="mt-4 text-sm text-primary-600 px-4"
          >
            No movement added for this account.
          </div>
          <hr v-else class="border-t" />
        </div>
      </div>

      <div
        v-if="movementsReconciliatedByAccount!.length === 0"
        class="mt-4 text-sm text-primary-300 rounded border bg-primary-800 p-4 -mx-4"
      >
        No movement needed for this activity.
      </div>
    </div>
  </div>
</template>
