// apps/ui-react/src/components/projects/project-select.tsx
import { useStore } from "zustand";
import type { UUID } from "crypto";
import { projectsStore } from "@/stores/projects";
import { Select, SelectContent, SelectItem, SelectTrigger } from "@/components/ui/select";
import { useMemo } from "react";
import { ChevronDown } from "lucide-react";

interface ProjectSelectProps {
  modelValue: UUID | null;
  onUpdateModelValue: (value: UUID | null) => void;
}

export function ProjectSelect({ modelValue, onUpdateModelValue }: ProjectSelectProps) {
  const projects = useStore(projectsStore, (state) => state.projects);

  const allProjects = [{ id: null, name: "No project", emoji: null }, ...projects];

  const selectedProject = useMemo(() => {
    if (!modelValue) return allProjects[0];
    return allProjects.find((p) => p.id === modelValue) || allProjects[0];
  }, [modelValue, allProjects]);

  return (
    <Select
      value={modelValue?.toString() || "null"}
      onValueChange={(value) => {
        onUpdateModelValue(value === "null" ? null : (value as UUID));
      }}
    >
      <SelectTrigger className="w-[180px]">
        <div className="flex items-center">
          {selectedProject.emoji && <span className="mr-2">{selectedProject.emoji}</span>}
          <span>{selectedProject.name}</span>
        </div>
        <ChevronDown className="size-4 text-muted-foreground" />
      </SelectTrigger>
      <SelectContent>
        {allProjects.map((project) => (
          <SelectItem key={project.id?.toString()} value={project.id?.toString() || "null"}>
            <div className="flex items-center">
              {project.emoji && <span className="w-6">{project.emoji}</span>}
              <span>{project.name}</span>
            </div>
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// apps/ui/src/components/projects/ProjectSelect.vue
<script setup lang="ts">
import { storeToRefs } from "pinia";
import type { UUID } from "crypto";

import { useProjectsStore } from "@/stores/projects";

const props = defineProps<{
  modelValue: UUID | null;
}>();
const emit = defineEmits(["update:model-value"]);

const projectsStore = useProjectsStore();
const { projects } = storeToRefs(projectsStore);
</script>

<template>
  <TSelect
    :model-value="modelValue"
    :items="[{ id: null, name: 'No project' }, ...projects]"
    item-value="id"
    item-text="name"
    placeholder="Project"
    @update:model-value="emit('update:model-value', $event)"
  >
    <template #selected="{ item }">
      <span v-if="item !== null" class="text-white">
        <span class="mr-2">{{ item.emoji }}</span>
        {{ item.name }}
      </span>
    </template>

    <template #item="{ item, selected }">
      <div
        :class="[
          selected ? 'font-medium' : 'font-normal',
          'truncate flex items-center',
        ]"
      >
        <div class="w-6">{{ item.emoji }}</div>
        {{ item.name }}
      </div>
    </template>
  </TSelect>
</template>
