// apps/ui/src/components/movements/filters/MovementFilter.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from "vue";

import MovementFilterOperatorMenu from "@/components/movements/filters/MovementFilterOperatorMenu.vue";
import MovementFilterValueMenu from "@/components/movements/filters/MovementFilterValueMenu.vue";

import {
  MovementFilterFields,
  OperatorsWithoutValue,
  type MovementFilter,
} from "@maille/core/movements";

const props = defineProps<{
  modelValue: MovementFilter;
}>();
const emit = defineEmits(["update:model-value", "delete"]);

const operatorMenu = ref<InstanceType<typeof MovementFilterOperatorMenu>>();
const valueMenu = ref<InstanceType<typeof MovementFilterValueMenu>>();

onMounted(() => {
  if (props.modelValue.operator === undefined) {
    operatorMenu.value!.click();
  } else if (props.modelValue.value === undefined) {
    if (valueMenu.value) {
      valueMenu.value.click();
    }
  }
});

watch(
  () => props.modelValue.operator,
  () => {
    if (props.modelValue.value === undefined) {
      nextTick(() => {
        if (valueMenu.value) {
          valueMenu.value.click();
        }
      });
    }
  },
);

const handleCloseOperator = () => {
  if (props.modelValue.operator === undefined) {
    emit("delete");
  }
};

const handleCloseValue = () => {
  if (
    props.modelValue.value === undefined ||
    (Array.isArray(props.modelValue.value) &&
      props.modelValue.value.length === 0)
  ) {
    emit("delete");
  }
};

const movementFilterField = computed(
  () =>
    MovementFilterFields.find((mff) => mff.value === props.modelValue.field)!,
);
</script>

<template>
  <div
    class="flex items-center rounded overflow-hidden h-7 border w-fit max-w-full bg-primary-800"
  >
    <div
      class="flex items-center px-2 text-sm h-7 text-white border-r font-medium"
    >
      <i class="mdi mt-0.5" :class="movementFilterField.icon" />
      <span class="ml-2 mr-1">
        {{ movementFilterField.text }}
      </span>
    </div>

    <MovementFilterOperatorMenu
      ref="operatorMenu"
      :model-value="modelValue.operator"
      :field="modelValue.field"
      @update:model-value="
        emit('update:model-value', { ...modelValue, operator: $event })
      "
      @close="handleCloseOperator"
    />

    <MovementFilterValueMenu
      v-if="modelValue.operator !== undefined"
      ref="valueMenu"
      :model-value="modelValue.value"
      :field="modelValue.field"
      @update:model-value="
        emit('update:model-value', { ...modelValue, value: $event })
      "
      @close="handleCloseValue"
    />

    <button
      class="flex items-center justify-center text-md w-7 h-7 hover:text-white hover:bg-primary-700 transition-colors shrink-0"
      @click="emit('delete')"
    >
      <i class="mdi mdi-close mt-0.5" />
    </button>
  </div>
</template>

// apps/ui-react/src/components/movements/filters/movement-filter.tsx
import { useEffect, useRef } from "react";
import { MovementFilterFields, type MovementFilter } from "@maille/core/movements";
import { X } from "lucide-react";
import { MovementFilterOperatorMenu } from "./movement-filter-operator-menu";
import { MovementFilterValueMenu } from "./movement-filter-value-menu";

interface MovementFilterProps {
  modelValue: MovementFilter;
  onUpdateModelValue: (value: MovementFilter) => void;
  onDelete: () => void;
}

export function MovementFilter({ modelValue, onUpdateModelValue, onDelete }: MovementFilterProps) {
  const operatorMenuRef = useRef<{ click: () => void }>(null);
  const valueMenuRef = useRef<{ click: () => void }>(null);

  useEffect(() => {
    if (modelValue.operator === undefined) {
      operatorMenuRef.current?.click();
    } else if (modelValue.value === undefined) {
      if (valueMenuRef.current) {
        valueMenuRef.current.click();
      }
    }
  }, [modelValue]);

  useEffect(() => {
    if (modelValue.operator !== undefined && modelValue.value === undefined) {
      setTimeout(() => {
        if (valueMenuRef.current) {
          valueMenuRef.current.click();
        }
      }, 0);
    }
  }, [modelValue.operator]);

  const handleCloseOperator = () => {
    if (modelValue.operator === undefined) {
      onDelete();
    }
  };

  const handleCloseValue = () => {
    if (
      modelValue.value === undefined ||
      (Array.isArray(modelValue.value) && modelValue.value.length === 0)
    ) {
      onDelete();
    }
  };

  const movementFilterField = MovementFilterFields.find((mff) => mff.value === modelValue.field);

  if (!movementFilterField) return null;

  return (
    <div className="flex items-center rounded overflow-hidden h-7 border w-fit max-w-full bg-primary-800">
      <div className="flex items-center px-2 text-sm h-7 text-white border-r font-medium">
        <i className={`mdi mt-0.5 ${movementFilterField.icon}`} aria-hidden="true" />
        <span className="ml-2 mr-1">{movementFilterField.text}</span>
      </div>

      <MovementFilterOperatorMenu
        ref={operatorMenuRef}
        modelValue={modelValue.operator}
        field={modelValue.field}
        onUpdateModelValue={(operator: any) => {
          onUpdateModelValue({ ...modelValue, operator });
        }}
        onClose={handleCloseOperator}
      />

      {modelValue.operator !== undefined && (
        <MovementFilterValueMenu
          ref={valueMenuRef}
          modelValue={modelValue.value}
          field={modelValue.field}
          onUpdateModelValue={(value: any) => {
            onUpdateModelValue({ ...modelValue, value });
          }}
          onClose={handleCloseValue}
        />
      )}

      <button
        className="flex items-center justify-center text-md w-7 h-7 hover:text-white hover:bg-primary-700 transition-colors shrink-0"
        onClick={onDelete}
        aria-label="Delete filter"
      >
        <X className="size-4 mt-0.5" />
      </button>
    </div>
  );
}
