// apps/ui-react/src/components/accounts/account-label.tsx
import { useStore } from "zustand";
import type { UUID } from "crypto";
import { accountsStore, ACCOUNT_TYPES_COLOR } from "@/stores/accounts";
import { useMemo } from "react";

interface AccountLabelProps {
  accountId: UUID;
  onlyUser?: boolean;
}

export function AccountLabel({ accountId, onlyUser = false }: AccountLabelProps) {
  const accounts = useStore(accountsStore, (state) => state.accounts);

  const account = useMemo(() => {
    return accounts.find((a) => a.id === accountId);
  }, [accounts, accountId]);

  if (!account) return null;

  return (
    <div className="flex items-center min-w-0 shrink-0">
      {!onlyUser && (
        <div
          className="size-4.5 rounded-xl shrink-0 -ml-1"
          style={{ backgroundColor: ACCOUNT_TYPES_COLOR[account.type] }}
        />
      )}
      <div className="font-medium text-ellipsis whitespace-nowrap overflow-hidden text-white ml-2 sm:ml-3">
        {account.name}
      </div>
    </div>
  );
}

// apps/ui/src/components/AccountLabel.vue
<script setup lang="ts">
import { useAccountsStore, ACCOUNT_TYPES_COLOR } from "@/stores/accounts";
import type { UUID } from "crypto";

import { computed } from "vue";

const accountStore = useAccountsStore();

const props = defineProps<{
  accountId: UUID;
}>();

const account = computed(() => {
  return accountStore.accounts.find((a) => a.id === props.accountId);
});
</script>

<template>
  <div v-if="account" class="flex items-center min-w-0 shrink-0">
    <div
      class="h-3 w-3 rounded-xl mr-2 sm:mr-3 shrink-0"
      :class="ACCOUNT_TYPES_COLOR[account.type]"
    />
    <div
      class="font-medium text-ellipsis whitespace-nowrap overflow-hidden text-white"
    >
      {{ account.name }}
    </div>
  </div>
</template>
