// apps/ui/src/components/UploadDropZone.vue
<script setup lang="ts">
import { ref } from "vue";

const emit = defineEmits(["file"]);

const overDrop = ref(false);
const fileUploadInput = ref<HTMLElement | null>(null);

const handleDropEvent = (event: DragEvent) => {
  if (event.dataTransfer) {
    emitFile(event.dataTransfer.files[0]);
  }
};

const handleFileInputEvent = (event: Event) => {
  if (event.target) {
    emitFile((event.target as HTMLInputElement).files![0]);
  }
};

const emitFile = (file: File) => {
  emit("file", file);
};
</script>

<template>
  <div
    class="py-4 flex flex-col items-center outline-dotted outline-primary-200 outline-2 rounded"
    :class="overDrop ? 'bg-primary-900' : ''"
    @drop.prevent="handleDropEvent($event)"
    @dragover.prevent="overDrop = true"
    @dragleave.prevent="overDrop = false"
  >
    <div class="my-2">
      <i class="mdi mdi-upload text-primary-100 text-4xl" />
    </div>
    <div class="text-primary-100 text-xs">Drag and drop here, or</div>

    <input
      ref="fileUploadInput"
      name="upload-file"
      type="file"
      hidden
      onclick="this.value = null;"
      @change="handleFileInputEvent($event)"
    />
    <TBtn class="mt-5" @click="fileUploadInput!.click()">
      Select from your computer
    </TBtn>

    <div class="mt-8 text-xs text-primary-200">File should be a valid CSV.</div>
  </div>
</template>

<style scoped></style>

// apps/ui-react/src/components/upload-drop-zone.tsx
import { useState, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Upload } from "lucide-react";

interface UploadDropZoneProps {
  onFile: (file: File) => void;
}

export function UploadDropZone({ onFile }: UploadDropZoneProps) {
  const [overDrop, setOverDrop] = useState(false);
  const fileUploadInput = useRef<HTMLInputElement>(null);

  const handleDropEvent = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    if (event.dataTransfer) {
      emitFile(event.dataTransfer.files[0]);
    }
    setOverDrop(false);
  };

  const handleFileInputEvent = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files) {
      emitFile(event.target.files[0]);
    }
  };

  const emitFile = (file: File) => {
    onFile(file);
  };

  return (
    <div
      className={`py-4 flex flex-col items-center outline-dotted outline-primary-200 outline-2 rounded ${
        overDrop ? "bg-primary-900" : ""
      }`}
      onDrop={handleDropEvent}
      onDragOver={(e) => {
        e.preventDefault();
        setOverDrop(true);
      }}
      onDragLeave={(e) => {
        e.preventDefault();
        setOverDrop(false);
      }}
    >
      <div className="my-2">
        <Upload className="text-primary-100 size-10" />
      </div>
      <div className="text-primary-100 text-xs">Drag and drop here, or</div>

      <input
        ref={fileUploadInput}
        name="upload-file"
        type="file"
        hidden
        onClick={(e) => {
          // @ts-ignore
          e.target.value = null;
        }}
        onChange={handleFileInputEvent}
      />
      <Button className="mt-5" variant="outline" onClick={() => fileUploadInput.current?.click()}>
        Select from your computer
      </Button>

      <div className="mt-8 text-xs text-primary-200">File should be a valid CSV.</div>
    </div>
  );
}
