// apps/ui-react/src/components/activities/filters/activity-filter-value-menu.tsx
import { forwardRef, useImperativeHandle, useRef, useState } from "react";
import { ChevronDown } from "lucide-react";
import { ActivityFilterDateValues, ActivityType } from "@maille/core/activities";
import type { ActivityFilter } from "@maille/core/activities";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { AccountSelect } from "@/components/accounts/account-select";

interface ActivityFilterValueMenuProps {
  modelValue: ActivityFilter["value"] | undefined;
  field: ActivityFilter["field"];
  onUpdateModelValue: (value: ActivityFilter["value"]) => void;
  onClose: () => void;
}

export const ActivityFilterValueMenu = forwardRef<
  { click: () => void },
  ActivityFilterValueMenuProps
>(({ modelValue, field, onUpdateModelValue, onClose }, ref) => {
  const inputRef = useRef<HTMLInputElement>(null);
  const selectRef = useRef<HTMLButtonElement>(null);
  const [textValue, setTextValue] = useState<string | undefined>(modelValue as string | undefined);
  const [open, setOpen] = useState(false);

  useImperativeHandle(ref, () => ({
    click: () => {
      if (inputRef.current) {
        inputRef.current.focus();
      } else if (selectRef.current) {
        selectRef.current.click();
      }
    },
  }));

  if (field === "date") {
    return (
      <Select
        value={modelValue as string | undefined}
        onValueChange={(value) => {
          onUpdateModelValue(value as ActivityFilter["value"]);
        }}
        onOpenChange={(isOpen) => {
          setOpen(isOpen);
          if (!isOpen) {
            onClose();
          }
        }}
      >
        <SelectTrigger
          ref={selectRef}
          className={`text-primary-100 hover:bg-primary-700 flex h-7 min-w-[24px] items-center border-r px-2 text-sm transition-colors hover:text-white ${
            open ? "bg-primary-700 text-white" : ""
          }`}
        >
          <SelectValue placeholder="Date value" />
          <ChevronDown className="ml-1 size-4" />
        </SelectTrigger>
        <SelectContent className="bg-primary-800 border-primary-600">
          {ActivityFilterDateValues.map((value) => (
            <SelectItem key={value} value={value} className="text-primary-100 hover:bg-primary-700">
              {value}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    );
  } else if (field === "amount") {
    return (
      <Input
        ref={inputRef}
        type="number"
        value={modelValue as number | undefined}
        onChange={(e) => {
          const value = e.target.value;
          onUpdateModelValue(value === "" ? undefined : parseFloat(value));
        }}
        onBlur={() => onClose()}
        className="hover:bg-primary-700 text-primary-100 h-7 border-r border-none bg-transparent px-2 text-sm hover:text-white focus:ring-0"
      />
    );
  } else if (field === "name" || field === "description") {
    return (
      <Input
        ref={inputRef}
        value={textValue}
        onChange={(e) => setTextValue(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            onUpdateModelValue(textValue);
          }
        }}
        onBlur={() => {
          onUpdateModelValue(textValue);
          onClose();
        }}
        className="hover:bg-primary-700 text-primary-100 h-7 min-w-0 border-none bg-transparent px-2 text-sm hover:text-white focus:ring-0"
      />
    );
  } else if (field === "type") {
    return (
      <Select
        value={modelValue as string | undefined}
        onValueChange={(value) => {
          onUpdateModelValue(value as ActivityFilter["value"]);
        }}
        onOpenChange={(isOpen) => {
          setOpen(isOpen);
          if (!isOpen) {
            onClose();
          }
        }}
      >
        <SelectTrigger
          ref={selectRef}
          className={`text-primary-100 hover:bg-primary-700 flex h-7 min-w-[24px] items-center border-r px-2 text-sm transition-colors hover:text-white ${
            open ? "bg-primary-700 text-white" : ""
          }`}
        >
          <SelectValue placeholder="Type value" />
          <ChevronDown className="ml-1 size-4" />
        </SelectTrigger>
        <SelectContent className="bg-primary-800 border-primary-600">
          {Object.values(ActivityType).map((value) => (
            <SelectItem key={value} value={value} className="text-primary-100 hover:bg-primary-700">
              {value}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    );
  } else if (field === "from_account" || field === "to_account") {
    return (
      <AccountSelect
        modelValue={modelValue && Array.isArray(modelValue) ? modelValue : []}
        onUpdateModelValue={(value) => {
          onUpdateModelValue(value);
        }}
        multiple
        borderless
        className="hover:bg-primary-700 border-r"
      />
    );
  }

  return null;
});

ActivityFilterValueMenu.displayName = "ActivityFilterValueMenu";

// apps/ui/src/components/activities/filters/ActivityFilterValueMenu.vue
<script setup lang="ts">
import { ref, nextTick } from "vue";

import AccountSelect from "@/components/accounts/AccountSelect.vue";

import { useActivitiesStore } from "@/stores/activities";

import {
  ActivityType,
  type ActivityFilter,
  ActivityFilterDateValues,
} from "@maille/core/activities";

const props = defineProps<{
  modelValue: ActivityFilter["value"] | undefined;
  field: ActivityFilter["field"];
}>();
const emit = defineEmits(["update:model-value", "close"]);

const { categories, subcategories } = useActivitiesStore();

const textValue = ref(props.modelValue);

const input = ref();

defineExpose({
  click: () => {
    if (input.value) {
      input.value.click();
    }
  },
});
</script>

<script lang="ts">
export default {
  components: { AccountSelect },
  inheritAttrs: false,
};
</script>

<template>
  <template v-if="field === 'date'">
    <TSelect
      ref="input"
      v-slot="{ open, text }"
      :model-value="modelValue"
      :items="ActivityFilterDateValues.map((v) => ({ value: v, text: v }))"
      @update:model-value="emit('update:model-value', $event)"
      @close="emit('close')"
    >
      <button
        class="flex items-center px-2 text-sm h-7 text-primary-100 hover:text-white hover:bg-primary-700 transition-colors border-r min-w-[24px]"
        :class="{
          'bg-primary-700 text-white': open,
        }"
      >
        <span class="block truncate"> {{ text }} </span>
      </button>
    </TSelect>
  </template>
  <template v-else-if="field === 'amount'">
    <TAmountInput
      ref="input"
      borderless
      class="text-sm px-2 border-r h-7 hover:bg-primary-700 text-primary-100 hover:text-white"
      :model-value="modelValue as number"
      v-bind="$attrs"
      @update:model-value="emit('update:model-value', $event)"
      @close="emit('close')"
    />
  </template>
  <template v-else-if="field === 'name' || field === 'description'">
    <TTextField
      ref="input"
      v-model="textValue as string | undefined"
      class="border-none min-w-0 bg-transparent hover:bg-primary-700"
      v-bind="$attrs"
      @keydown.enter="emit('update:model-value', textValue)"
      @blur="
        emit('update:model-value', textValue);
        nextTick(() => emit('close'));
      "
    />
  </template>
  <template v-if="field === 'type'">
    <TSelect
      ref="input"
      v-slot="{ open, text }"
      :model-value="modelValue"
      :items="[
        { id: ActivityType.REVENUE, name: 'Revenue' },
        { id: ActivityType.EXPENSE, name: 'Expense' },
        { id: ActivityType.INVESTMENT, name: 'Investment' },
        { id: ActivityType.NEUTRAL, name: 'Neutral' },
      ]"
      item-value="id"
      item-text="name"
      multiple
      @update:model-value="emit('update:model-value', $event)"
      @close="emit('close')"
    >
      <button
        class="flex items-center px-2 text-sm h-7 text-primary-100 hover:text-white hover:bg-primary-700 transition-colors border-r min-w-[24px]"
        :class="{
          'bg-primary-700 text-white': open,
        }"
      >
        <span class="block truncate"> {{ text }} </span>
      </button>
    </TSelect>
  </template>
  <template v-if="field === 'category'">
    <TSelect
      ref="input"
      v-slot="{ open, text }"
      :model-value="modelValue"
      :items="categories"
      item-value="id"
      item-text="name"
      multiple
      @update:model-value="emit('update:model-value', $event)"
      @close="emit('close')"
    >
      <button
        class="flex items-center px-2 text-sm h-7 text-primary-100 hover:text-white hover:bg-primary-700 transition-colors border-r min-w-[24px]"
        :class="{
          'bg-primary-700 text-white': open,
        }"
      >
        <span class="block truncate"> {{ text }} </span>
      </button>
    </TSelect>
  </template>
  <template v-if="field === 'subcategory'">
    <TSelect
      ref="input"
      v-slot="{ open, text }"
      :model-value="modelValue"
      :items="subcategories"
      item-value="id"
      item-text="name"
      multiple
      @update:model-value="emit('update:model-value', $event)"
      @close="emit('close')"
    >
      <button
        class="flex items-center px-2 text-sm h-7 text-primary-100 hover:text-white hover:bg-primary-700 transition-colors border-r min-w-[24px]"
        :class="{
          'bg-primary-700 text-white': open,
        }"
      >
        <span class="block truncate"> {{ text }} </span>
      </button>
    </TSelect>
  </template>
  <template v-if="field === 'from_account' || field === 'to_account'">
    <AccountSelect
      ref="input"
      :model-value="modelValue"
      multiple
      borderless
      class="border-r hover:bg-gray-50"
      @update:model-value="emit('update:model-value', $event)"
      @close="emit('close')"
    />
  </template>
</template>
