// apps/ui/src/containers/activities/ActivityLiabilities.vue
<script setup lang="ts">
import { computed, ref } from "vue";

import { useLiabilitiesStore } from "@/stores/liabilities";

import AccountLabel from "@/components/AccountLabel.vue";

import { getCurrencyFormatter } from "@/utils/currency";

import type { Activity } from "@maille/core/activities";

const liabilitiesStore = useLiabilitiesStore();

const props = defineProps<{ activity: Activity }>();

const showLiabilities = ref(true);

const activityLiabilities = computed(() =>
  liabilitiesStore.liabilities.filter(
    (l) => l.activity === props.activity.id && l.amount !== 0,
  ),
);
</script>
<template>
  <div class="border-b py-6 px-4 sm:px-8">
    <div class="flex items-center">
      <div
        class="-ml-2 text-sm font-medium text-primary-100 px-2 rounded h-7 hover:text-white flex items-center"
        @click="showLiabilities = !showLiabilities"
      >
        Liabilities
        <i
          class="mdi ml-2"
          :class="showLiabilities ? 'mdi-menu-down' : 'mdi-menu-up'"
        />
      </div>
    </div>

    <div
      v-show="showLiabilities"
      class="mt-4 mb-2 -mx-4 rounded border bg-primary-800"
    >
      <div
        v-for="(liability, index) in activityLiabilities"
        :key="liability.account"
        class="h-10 flex items-center justify-center text-sm hover:bg-primary-700 px-4"
        :class="[index !== activityLiabilities.length - 1 && 'border-b']"
      >
        <AccountLabel :account-id="liability.account" class="text-sm ml-0.5" />

        <div class="flex-1" />

        <span class="font-mono">
          {{ getCurrencyFormatter().format(liability.amount) }}
        </span>
      </div>
      <div
        v-if="activityLiabilities!.length === 0"
        class="text-sm text-primary-300 px-4 py-3"
      >
        No liability detected for this activity.
      </div>
    </div>
  </div>
</template>

// apps/ui-react/src/components/activities/activity-liabilities.tsx
import { type Activity } from "@maille/core/activities";

import { Button } from "@/components/ui/button";
import { getCurrencyFormatter } from "@/lib/utils";

interface ActivityLiabilitiesProps {
  activity: Activity;
}

export function ActivityLiabilities({ activity }: ActivityLiabilitiesProps) {
  const currencyFormatter = getCurrencyFormatter();

  const liabilities: any[] = []; // This would come from a store or API

  return (
    <div className="px-4 py-6 sm:px-8">
      <div className="flex items-center">
        <div className="text-sm font-medium">Liabilities</div>
      </div>

      {liabilities.length === 0 ? (
        <div className="py-4 text-sm text-muted-foreground">
          No transaction added for this activity.
        </div>
      ) : (
        <div className="space-y-4">
          {liabilities.map((liability: any) => (
            <div key={liability.id} className="border-b pb-4">
              <div className="flex items-center justify-between">
                <div>
                  <div className="font-medium text-white">{liability.name}</div>
                  <div className="text-primary-400 text-sm">
                    {currencyFormatter.format(liability.amount)}
                  </div>
                </div>
                <div className="text-right">
                  <Button variant="ghost" size="icon">
                    <span className="sr-only">Edit</span>
                    {/* Edit icon would go here */}
                  </Button>
                  <Button variant="ghost" size="icon" className="ml-2">
                    <span className="sr-only">Delete</span>
                    {/* Delete icon would go here */}
                  </Button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
