// apps/ui/src/containers/activities/AddTransactionButton.vue
<script setup lang="ts">
import { ref } from "vue";

import {
  TransitionRoot,
  TransitionChild,
  Dialog,
  DialogPanel,
  DialogTitle,
} from "@headlessui/vue";

import AccountSelect from "@/components/accounts/AccountSelect.vue";

import type { Activity } from "@maille/core/activities";
import { useActivitiesStore } from "@/stores/activities";
import type { UUID } from "crypto";
import { useEventsStore } from "@/stores/events";
import { addTransactionMutation } from "@/mutations/activities";

const activitiesStore = useActivitiesStore();

const props = defineProps<{
  activity: Activity;
}>();

const addNewTransactionDialog = ref({
  show: false,
  amount: undefined as number | undefined,
  fromAccount: undefined as UUID | undefined,
  toAccount: undefined as UUID | undefined,
});

const resetAddNewTransactionDialog = () => {
  addNewTransactionDialog.value = {
    show: false,
    amount: undefined,
    fromAccount: undefined,
    toAccount: undefined,
  };
};

const eventsStore = useEventsStore();

const addNewTransaction = async () => {
  if (addNewTransactionDialog.value.amount === undefined) return;
  else if (addNewTransactionDialog.value.fromAccount === undefined) return;
  else if (addNewTransactionDialog.value.toAccount === undefined) return;

  const transaction = activitiesStore.addNewTransaction(
    props.activity.id,
    addNewTransactionDialog.value.amount,
    addNewTransactionDialog.value.fromAccount,
    addNewTransactionDialog.value.toAccount,
  );

  eventsStore.sendEvent({
    name: "addTransaction",
    mutation: addTransactionMutation,
    variables: {
      activityId: props.activity.id,
      ...transaction,
    },
    rollbackData: undefined,
  });

  resetAddNewTransactionDialog();
};

const open = () => {
  addNewTransactionDialog.value.show = true;
};
</script>

<template>
  <TTooltip text="Add a transaction">
    <button
      type="button"
      class="inline-flex items-center justify-center w-6 h-6 transition text-primary-100 hover:text-white bg-primary-700 hover:bg-primary-600 border rounded-md"
      @click="open"
    >
      <i class="mdi mdi-plus text-base" />
    </button>
  </TTooltip>

  <TransitionRoot appear :show="addNewTransactionDialog.show" as="template">
    <Dialog
      as="div"
      class="relative z-50"
      @close="resetAddNewTransactionDialog"
    >
      <div class="fixed inset-0 overflow-y-auto">
        <div
          class="flex min-h-full items-center justify-center p-4 text-center"
        >
          <TransitionChild
            as="template"
            enter="duration-100 ease-out"
            enter-from="opacity-0 scale-95"
            enter-to="opacity-100 scale-100"
            leave="duration-100 ease-in"
            leave-from="opacity-100 scale-100"
            leave-to="opacity-0 scale-95"
          >
            <DialogPanel
              class="w-full max-w-xl transform overflow-hidden rounded-lg bg-primary-800 text-left align-middle shadow-2xl transition-all border"
            >
              <DialogTitle as="div" class="flex border-b pb-4 pt-5 px-8">
                <div class="text-white font-medium">Add a new transaction</div>
                <div class="flex-1" />
                <button
                  class="inline-flex items-center justify-center w-6 h-6 transition text-primary-500 hover:text-primary-100 min-w-6 shrink-0"
                  @click="resetAddNewTransactionDialog"
                >
                  <i class="mdi mdi-close text-lg" />
                </button>
              </DialogTitle>

              <div class="px-8 py-6">
                <div class="flex flex-col sm:flex-row sm:items-center text-sm">
                  <div class="text-sm text-primary-600">Amount</div>
                  <div class="flex-1" />
                  <TAmountInput
                    v-model="addNewTransactionDialog.amount"
                    class="w-full sm:w-56 mt-2 sm:mt-0"
                  />
                </div>

                <div
                  class="mt-4 flex flex-col sm:flex-row sm:items-center text-sm"
                >
                  <div class="text-sm text-primary-600">From account</div>
                  <div class="flex-1" />
                  <AccountSelect
                    v-model="addNewTransactionDialog.fromAccount"
                    class="w-full sm:w-56 mt-2 sm:mt-0"
                  />
                </div>

                <div
                  class="mt-4 flex flex-col sm:flex-row sm:items-center text-sm"
                >
                  <div class="text-sm text-primary-600">To account</div>
                  <div class="flex-1" />
                  <AccountSelect
                    v-model="addNewTransactionDialog.toAccount"
                    class="w-full sm:w-56 mt-2 sm:mt-0"
                  />
                </div>
              </div>

              <div class="border-t px-8 py-4 flex justify-end">
                <TBtn @click="addNewTransaction"> Create transaction </TBtn>
              </div>
            </DialogPanel>
          </TransitionChild>
        </div>
      </div>
    </Dialog>
  </TransitionRoot>
</template>

// apps/ui-react/src/components/activities/add-transaction-button.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import type { Activity } from "@maille/core/activities";
import { Plus } from "lucide-react";
import { useState } from "react";
import { useForm, Controller } from "react-hook-form";
import z from "zod";

import { AccountSelect } from "@/components/accounts/account-select";
import { AmountInput } from "@/components/ui/amount-input";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Field, FieldError, FieldLabel } from "@/components/ui/field";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { addTransactionMutation } from "@/mutations/activities";
import { activitiesStore } from "@/stores/activities";
import { syncStore } from "@/stores/sync";

// Form schema using zod
const formSchema = z.object({
  amount: z.number().min(0.01, "Amount must be greater than 0"),
  fromAccount: z.string().min(1, "From account is required"),
  toAccount: z.string().min(1, "To account is required"),
});

type FormValues = z.infer<typeof formSchema>;

interface AddTransactionButtonProps {
  activity: Activity;
  className?: string;
}

export function AddTransactionButton({
  activity,
  className,
}: AddTransactionButtonProps) {
  const [showDialog, setShowDialog] = useState(false);

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      amount: 0,
      fromAccount: "",
      toAccount: "",
    },
  });

  const { control, handleSubmit, reset } = form;

  const handleAddTransaction = (data: FormValues) => {
    const transaction = activitiesStore
      .getState()
      .addNewTransaction(
        activity.id,
        data.amount,
        data.fromAccount,
        data.toAccount,
      );

    syncStore.getState().mutate({
      name: "addTransaction",
      mutation: addTransactionMutation,
      variables: {
        activityId: activity.id,
        ...transaction,
      },
      rollbackData: undefined,
    });

    reset();
    setShowDialog(false);
  };

  const resetDialog = () => {
    setShowDialog(false);
    reset();
  };

  return (
    <>
      <Tooltip>
        <TooltipTrigger asChild>
          <Button
            onClick={() => setShowDialog(true)}
            className={className}
            variant="outline"
            size="icon"
          >
            <Plus className="h-4 w-4" />
          </Button>
        </TooltipTrigger>
        <TooltipContent>
          <p>Add a transaction</p>
        </TooltipContent>
      </Tooltip>

      <Dialog open={showDialog} onOpenChange={resetDialog}>
        <DialogContent className="bg-primary-800 border-primary-700 max-w-xl text-white">
          <DialogHeader>
            <DialogTitle className="font-medium text-white">
              Add a new transaction
            </DialogTitle>
          </DialogHeader>

          <form onSubmit={handleSubmit(handleAddTransaction)} className="py-4">
            <Controller
              name="amount"
              control={control}
              render={({ field, fieldState }) => (
                <Field data-invalid={fieldState.invalid} className="mb-4">
                  <FieldLabel htmlFor="amount">Amount</FieldLabel>
                  <AmountInput
                    id="amount"
                    value={field.value}
                    onChange={field.onChange}
                    className="w-full sm:w-56"
                  />
                  {fieldState.invalid && (
                    <FieldError errors={[fieldState.error]} />
                  )}
                </Field>
              )}
            />

            <Controller
              name="fromAccount"
              control={control}
              render={({ field, fieldState }) => (
                <Field data-invalid={fieldState.invalid} className="mb-4">
                  <FieldLabel htmlFor="fromAccount">From account</FieldLabel>
                  <AccountSelect
                    modelValue={field.value}
                    onUpdateModelValue={field.onChange}
                    className="w-full sm:w-56"
                  />
                  {fieldState.invalid && (
                    <FieldError errors={[fieldState.error]} />
                  )}
                </Field>
              )}
            />

            <Controller
              name="toAccount"
              control={control}
              render={({ field, fieldState }) => (
                <Field data-invalid={fieldState.invalid} className="mb-4">
                  <FieldLabel htmlFor="toAccount">To account</FieldLabel>
                  <AccountSelect
                    modelValue={field.value}
                    onUpdateModelValue={field.onChange}
                    className="w-full sm:w-56"
                  />
                  {fieldState.invalid && (
                    <FieldError errors={[fieldState.error]} />
                  )}
                </Field>
              )}
            />

            <DialogFooter>
              <Button
                type="submit"
                className="bg-primary-700 hover:bg-primary-600"
              >
                Create transaction
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </>
  );
}
