// apps/ui/src/containers/activities/ExportActivitiesButton.vue
<script setup lang="ts">
import { computed } from "vue";

import { stringify } from "csv-stringify/browser/esm/sync";

import { useViewsStore } from "@/stores/views";

import type { Activity } from "@maille/core/activities";
import { verifyActivityFilter } from "@maille/core/activities";

const props = defineProps<{
  viewId: string;
  activities: Activity[];
}>();

const activityView = computed(() =>
  useViewsStore().getActivityView(props.viewId),
);

const filteredActivities = computed(() => {
  return props.activities.filter((activity) => {
    if (activityView.value.filters.length === 0) return true;

    return activityView.value.filters
      .map((filter) => {
        return verifyActivityFilter(filter, activity);
      })
      .every((f) => f);
  });
});

const exportActivities = () => {
  const csvFile = stringify([
    ["number", "date", "name", "amount"],
    ...filteredActivities.value.map((a) => [
      a.number,
      a.date.format("YYYY-MM-DD"),
      a.name,
      a.amount,
    ]),
  ]);

  const url = window.URL.createObjectURL(new Blob([csvFile]));
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", `activities_export.csv`);
  document.body.appendChild(link);
  link.click();
  link.remove();
};
</script>

<template>
  <TTooltip text="Export activities">
    <button
      type="button"
      class="inline-flex items-center justify-center transition text-primary-100 hover:text-white hover:border-primary-300 rounded h-7 w-7 border border-dashed"
      @click="exportActivities"
    >
      <i class="mdi mdi-download mt-0.5" />
    </button>
  </TTooltip>
</template>

// apps/ui-react/src/components/activities/export-activities-button.tsx
import { verifyActivityFilter, type Activity } from "@maille/core/activities";
import { stringify } from "csv-stringify/browser/esm/sync";
import { Download } from "lucide-react";
import * as React from "react";

import { Button } from "@/components/ui/button";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { useViews } from "@/stores/views";

interface ExportActivitiesButtonProps {
  viewId: string;
  activities: Activity[];
  className?: string;
}

export function ExportActivitiesButton({
  viewId,
  activities,
  className,
}: ExportActivitiesButtonProps) {
  const activityView = useViews((state) =>
    state.getActivityView(viewId),
  );

  const filteredActivities = React.useMemo(() => {
    return activities.filter((activity) => {
      if (activityView.filters.length === 0) return true;

      return activityView.filters
        .map((filter) => {
          return verifyActivityFilter(filter, activity);
        })
        .every((f) => f);
    });
  }, [activities, activityView.filters]);

  const exportActivities = () => {
    const csvFile = stringify([
      ["number", "date", "name", "amount"],
      ...filteredActivities.map((a) => [
        a.number,
        a.date.toISOString().split("T")[0], // Format date as YYYY-MM-DD
        a.name,
        a.amount,
      ]),
    ]);

    const url = window.URL.createObjectURL(new Blob([csvFile]));
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `activities_export.csv`);
    document.body.appendChild(link);
    link.click();
    link.remove();
  };

  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <Button
          variant="ghost"
          size="icon"
          className={className}
          onClick={exportActivities}
        >
          <Download className="h-4 w-4" />
        </Button>
      </TooltipTrigger>
      <TooltipContent>
        <p>Export activities</p>
      </TooltipContent>
    </Tooltip>
  );
}
